#!/usr/bin/env python3
"""Persist a Dirac pharmacophore model and its screening run into the database.

Consumes the facet's own export document (format 'dirac-pharmacophore-model',
version 1) plus, optionally, the screening result recorded alongside it, and
writes:

    bio.target / bio.structure / bio.structure_ligand   the model's origin
    design.pharmacophore_model + _feature               the model itself
    design.screening_run + design.screening_hit         what it retrieved

Emits SQL on stdout; pipe it to psql.

    backend/env/bin/python backend/db/load_pharmacophore.py export.json \\
        | psql -U ivan -d dirac -v ON_ERROR_STOP=1

The join that makes this worth doing: screening hits are resolved to
REGISTERED compounds through the library alias written by load_library.py, so
a hit stops being a string in a browser panel and becomes a row that can be
joined to assay results, projects, and every other compound-level fact.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

# PDB entries the lab ships fixtures for. Structure metadata is a FACT about
# the entry, not about our session, so it is recorded once here rather than
# inferred from a filename at load time.
KNOWN_STRUCTURES = {
    '1CBS': {'target': 'Cellular retinoic acid-binding protein 2', 'uniprot': 'P29373',
             'organism': 'Homo sapiens', 'method': 'xray', 'resolution': 1.80,
             'ligand_comp': 'REA'},
    '4HHB': {'target': 'Hemoglobin', 'uniprot': 'P69905', 'organism': 'Homo sapiens',
             'method': 'xray', 'resolution': 1.74, 'ligand_comp': 'HEM'},
    '1EMA': {'target': 'Green fluorescent protein', 'uniprot': 'P42212',
             'organism': 'Aequorea victoria', 'method': 'xray', 'resolution': 1.90,
             'ligand_comp': None},
}

# The library id whose registered compound IS the deposited ligand, where the
# two coincide. Asserted, not guessed: 1CBS's REA is retinoic acid.
LIGAND_TO_LIBRARY_ID = {'REA': 'retinoic-acid', 'HEM': None}


def s(value) -> str:
    if value is None:
        return 'NULL'
    return "'" + str(value).replace("'", "''") + "'"


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    doc = json.loads(Path(argv[1]).read_text())
    model = doc.get('model', doc)
    screening = doc.get('screening')

    if model.get('format') != 'dirac-pharmacophore-model':
        print('-- ABORT: not a dirac-pharmacophore-model document', file=sys.stderr)
        return 1
    if model.get('version') != 1:
        print(f"-- ABORT: unsupported model version {model.get('version')}", file=sys.stderr)
        return 1

    src = model.get('source') or {}
    pdb_id = (src.get('structureId') or '').strip() or None
    ligand_label = src.get('ligandLabel')
    features = model['features']
    was_edited = any(f.get('origin') == 'user' for f in features)
    model_name = f"{pdb_id or 'manual'}-{(ligand_label or 'model').split(' ')[0]}"

    out: list[str] = []
    w = out.append
    w('-- Generated by backend/db/load_pharmacophore.py — do not edit by hand.')
    w('BEGIN;')

    meta = KNOWN_STRUCTURES.get((pdb_id or '').upper())
    if meta:
        w(f"""
INSERT INTO bio.target (name, kind, uniprot, organism)
VALUES ({s(meta['target'])}, 'protein', {s(meta['uniprot'])}, {s(meta['organism'])})
ON CONFLICT (name) DO NOTHING;

INSERT INTO bio.structure (pdb_id, target_id, method, resolution_a)
SELECT {s(pdb_id.upper())}, t.id, {s(meta['method'])}::bio.structure_method, {meta['resolution']}
  FROM bio.target t WHERE t.name = {s(meta['target'])}
ON CONFLICT (pdb_id) DO NOTHING;""")

        comp = meta['ligand_comp']
        if comp:
            lib_id = LIGAND_TO_LIBRARY_ID.get(comp)
            # auth chain/seq come from the facet's ligand label ("REA · A:200").
            chain, seq = 'A', 0
            if ligand_label and ':' in ligand_label:
                tail = ligand_label.split('·')[-1].strip()
                if ':' in tail:
                    chain, seq_text = tail.split(':', 1)
                    chain = chain.strip()
                    seq = int(''.join(ch for ch in seq_text if ch.isdigit()) or 0)
            compound_expr = (
                f"(SELECT a.compound_id FROM chem.compound_alias a "
                f"WHERE a.kind='internal' AND a.alias LIKE {s('dirac-lib:' + lib_id + ':%')} LIMIT 1)"
                if lib_id else 'NULL'
            )
            w(f"""
INSERT INTO bio.structure_ligand (structure_id, comp_id, auth_chain, auth_seq_id, compound_id)
SELECT st.id, {s(comp)}, {s(chain)}, {seq}, {compound_expr}
  FROM bio.structure st WHERE st.pdb_id = {s(pdb_id.upper())}
ON CONFLICT DO NOTHING;""")

    w(f"""
INSERT INTO design.pharmacophore_model
    (id, name, structure_id, source_pdb_id, source_ligand_label, source_compound_id,
     was_edited, model_json)
SELECT gen_random_uuid(), {s(model_name)},
       (SELECT id FROM bio.structure WHERE pdb_id = {s((pdb_id or '').upper())}),
       {s((pdb_id or '').upper() or None)}, {s(ligand_label)},
       (SELECT sl.compound_id FROM bio.structure_ligand sl
          JOIN bio.structure st ON st.id = sl.structure_id
         WHERE st.pdb_id = {s((pdb_id or '').upper())} LIMIT 1),
       {str(was_edited).lower()}, {s(json.dumps(model))}::jsonb;""")

    for feature in features:
        px, py, pz = feature['position']
        direction = feature.get('direction')
        dx, dy, dz = direction if direction else (None, None, None)
        w(f"""
INSERT INTO design.pharmacophore_feature
    (model_id, feature_no, kind, x, y, z, dx, dy, dz, radius_a, enabled, origin)
SELECT id, {feature['id']}, {s(feature['kind'])}::design.pharmacophore_kind,
       {px:.4f}, {py:.4f}, {pz:.4f},
       {'NULL' if dx is None else f'{dx:.4f}'},
       {'NULL' if dy is None else f'{dy:.4f}'},
       {'NULL' if dz is None else f'{dz:.4f}'},
       {feature['radius']:.2f}, {str(feature.get('enabled', True)).lower()},
       {s(feature.get('origin', 'ligand'))}::design.feature_origin
  FROM design.pharmacophore_model
 WHERE name = {s(model_name)}
 ORDER BY created_at DESC LIMIT 1;""")

    if screening:
        req = screening['required']
        w(f"""
INSERT INTO design.screening_run
    (id, model_id, mode, library_name, library_size, required, n_screened, n_matched,
     engine_toolkit_id)
SELECT '{'{:0>8}'.format('')}'::uuid, m.id, 'topological', 'dirac-designer-library',
       {screening['screened'] + screening['invalid']}, {s(json.dumps(req))}::jsonb,
       {screening['screened']}, {screening['matched']},
       (SELECT id FROM meta.toolkit WHERE name='rdkit' ORDER BY version DESC LIMIT 1)
  FROM design.pharmacophore_model m
 WHERE m.name = {s(model_name)}
 ORDER BY m.created_at DESC LIMIT 1;""".replace("'00000000'::uuid", 'gen_random_uuid()'))

        for verdict in screening['verdicts']:
            w(f"""
INSERT INTO design.screening_hit (run_id, compound_id, matched, counts)
SELECT r.id,
       (SELECT a.compound_id FROM chem.compound_alias a
         WHERE a.kind='internal' AND a.alias LIKE {s('dirac-lib:' + verdict['id'] + ':%')} LIMIT 1),
       {str(verdict['matched']).lower()}, {s(json.dumps(verdict['counts']))}::jsonb
  FROM design.screening_run r
  JOIN design.pharmacophore_model m ON m.id = r.model_id
 WHERE m.name = {s(model_name)}
   AND EXISTS (SELECT 1 FROM chem.compound_alias a
                WHERE a.kind='internal' AND a.alias LIKE {s('dirac-lib:' + verdict['id'] + ':%')})
 ORDER BY r.ran_at DESC LIMIT 1
ON CONFLICT DO NOTHING;""")

    w('COMMIT;')
    print(f"-- model '{model_name}': {len(features)} features"
          + (f", screening {screening['matched']}/{screening['screened']}" if screening else ''),
          file=sys.stderr)
    sys.stdout.write('\n'.join(out) + '\n')
    return 0


if __name__ == '__main__':
    raise SystemExit(main(sys.argv))
