import { LigandDepiction } from '../../chemistry.backend.perception.rdkit-wasm.editable/ligand-depiction';
import { getRDKit } from '../../chemistry.backend.perception.rdkit-wasm.editable/semantic-chemistry-rdkit';

type ElementSymbol = 'C' | 'N' | 'O' | 'S' | 'F' | 'Cl' | 'Br';
type BondOrder = 1 | 2 | 3;
type SketchAtom = { id: number; element: ElementSymbol; x: number; y: number };
type SketchBond = { id: number; a: number; b: number; order: BondOrder };
type SketchState = { atoms: SketchAtom[]; bonds: SketchBond[]; selectedAtom: number | null; selectedBond: number | null };
export type SketchedMolecule = { id: string; smiles: string; molblock: string; atomCount: number };

const escapeHtml = (value: string) => value.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
const cloneState = (s: SketchState): SketchState => ({ atoms: s.atoms.map(a => ({ ...a })), bonds: s.bonds.map(b => ({ ...b })), selectedAtom: s.selectedAtom, selectedBond: s.selectedBond });

function bondLines(a: SketchAtom, b: SketchAtom, order: BondOrder): string {
    const dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||1,ox=-dy/l*4.2,oy=dx/l*4.2;
    const line=(o:number,w=2.4)=>`<line x1="${a.x+ox*o}" y1="${a.y+oy*o}" x2="${b.x+ox*o}" y2="${b.y+oy*o}" stroke-width="${w}"/>`;
    return order===1?line(0,3):order===2?line(-.55,2.2)+line(.55,2.2):line(-1,1.8)+line(0,1.8)+line(1,1.8);
}

function writeMolblock(name:string,atoms:SketchAtom[],bonds:SketchBond[]):string {
    const pad=(v:number,w:number)=>String(v).padStart(w,' '),coord=(v:number)=>v.toFixed(4).padStart(10,' '),index=new Map(atoms.map((a,i)=>[a.id,i+1]));
    const lines=[name||'Dirac proposal','  DIRAC    2D','Edited in the FEP ligand workspace',`${pad(atoms.length,3)}${pad(bonds.length,3)}  0  0  0  0  0  0  0  0  1 V2000`];
    atoms.forEach(a=>lines.push(`${coord((a.x-420)/38)}${coord((260-a.y)/38)}${coord(0)} ${a.element.padEnd(3,' ')} 0  0  0  0  0  0  0  0  0  0  0  0`));
    bonds.forEach(b=>lines.push(`${pad(index.get(b.a)||0,3)}${pad(index.get(b.b)||0,3)}${pad(b.order,3)}  0  0  0  0`)); lines.push('M  END'); return lines.join('\n');
}

function parseMolblock(molblock:string):{atoms:SketchAtom[];bonds:SketchBond[]} {
    const lines=molblock.split(/\r?\n/),atomCount=Number.parseInt(lines[3]?.slice(0,3).trim()||'0',10),bondCount=Number.parseInt(lines[3]?.slice(3,6).trim()||'0',10); if (!atomCount) throw new Error('The imported record contains no atoms.');
    const raw=Array.from({ length: atomCount },(_,i)=>({ x: Number.parseFloat(lines[4+i]?.slice(0,10)||'0'),y: Number.parseFloat(lines[4+i]?.slice(10,20)||'0'),element: (lines[4+i]?.slice(31,34).trim()||'C') as ElementSymbol }));
    const minX=Math.min(...raw.map(a=>a.x)),maxX=Math.max(...raw.map(a=>a.x)),minY=Math.min(...raw.map(a=>a.y)),maxY=Math.max(...raw.map(a=>a.y)),scale=Math.min(620/Math.max(1,maxX-minX),390/Math.max(1,maxY-minY),72),cx=(minX+maxX)/2,cy=(minY+maxY)/2;
    const atoms=raw.map((a,i)=>({ id: i+1,element: a.element,x: 420+(a.x-cx)*scale,y: 260-(a.y-cy)*scale }));
    const bonds=Array.from({ length: bondCount },(_,i)=>{ const line=lines[4+atomCount+i]||''; return { id: i+1,a: Number.parseInt(line.slice(0,3).trim(),10),b: Number.parseInt(line.slice(3,6).trim(),10),order: Math.max(1,Math.min(3,Number.parseInt(line.slice(6,9).trim(),10)||1)) as BondOrder }; }); return { atoms,bonds };
}

export class MoleculeSketcher {
    private atoms:SketchAtom[]=[]; private bonds:SketchBond[]=[]; private parent:SketchedMolecule|null=null; private parentGraph:{atoms:SketchAtom[];bonds:SketchBond[]}|null=null;
    private selectedAtom:number|null=null; private selectedBond:number|null=null; private element:ElementSymbol='C'; private bondOrder:BondOrder=1; private history:SketchState[]=[]; private future:SketchState[]=[]; private nextAtomId=1; private nextBondId=1; private dragAtom:number|null=null; private dragMoved=false; private status='IMPORT A REFERENCE OR START A BLANK MOLECULE'; private returnFocus:HTMLElement|null=null;
    constructor(private readonly host:HTMLElement,private readonly onAdd:(molecule:SketchedMolecule)=>void) { this.host.tabIndex=-1; this.host.innerHTML=this.shell(); this.bind(); this.host.addEventListener('keydown',event=>this.keydown(event)); this.host.addEventListener('cancel',event=>{ event.preventDefault(); this.close(); }); this.render(); }
    open():void { this.returnFocus=document.activeElement instanceof HTMLElement?document.activeElement:null; [...this.host.parentElement!.children].forEach(element=>{ if (element!==this.host)(element as HTMLElement).inert=true; }); if (this.host instanceof HTMLDialogElement&&!this.host.open) this.host.showModal(); this.host.classList.add('open'); this.host.setAttribute('aria-hidden','false'); this.host.querySelector<HTMLInputElement>('#parent-smiles')?.focus(); }
    close():void { this.host.classList.remove('open'); this.host.setAttribute('aria-hidden','true'); if (this.host instanceof HTMLDialogElement&&this.host.open) this.host.close(); [...this.host.parentElement!.children].forEach(element=>(element as HTMLElement).inert=false); this.returnFocus?.focus(); }
    private keydown(event:KeyboardEvent):void { if (event.key==='Escape') { event.preventDefault(); this.close(); return; } if (event.key!=='Tab') return; const focusable=[...this.host.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(element=>element.offsetParent!==null); if (!focusable.length) return; const first=focusable[0],last=focusable[focusable.length-1]; if (event.shiftKey&&document.activeElement===first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey&&document.activeElement===last) { event.preventDefault(); first.focus(); } }

    private shell():string {
return `<div class="sketcher-shell ligand-editor-shell">
      <header class="editor-topbar fep-topbar"><div class="editor-title"><button id="sketch-close" aria-label="Back to FEP campaign">←</button><span><small>MOTIF WORKBENCH · FEP · LIGAND DESIGN</small><b id="sketcher-title">PARENT → PROPOSAL EDITOR</b></span></div><div class="workspace-mode-tabs editor-steps"><button class="active">1 · IMPORT PARENT</button><button>2 · EDIT PROPOSAL</button><button>3 · REVIEW CHANGE</button></div><div class="editor-boundary"><i></i><span><b>LOCAL CHEMISTRY EDITOR</b><small>RDKIT VALIDATION · NO JOB SUBMITTED</small></span></div></header>
      <div class="ligand-editor-body">
        <aside class="parent-workspace"><div class="editor-pane-head"><span><small>IMMUTABLE SOURCE</small><b>PARENT MOLECULE</b></span><em>READ-ONLY</em></div>
          <section class="parent-import"><label><span>SMILES / CXSMILES</span><div><input id="parent-smiles" placeholder="Paste a standard molecular identity"><button id="load-parent-smiles">LOAD</button></div></label><div class="import-divider"><span>OR</span></div><label class="molecule-file"><input id="parent-file" type="file" accept=".sdf,.sd,.mol,.smi,.smiles,.txt"><b>UPLOAD MOL / SDF</b><small>First molecular record · 2D or 3D coordinates accepted</small></label><button id="start-blank" class="wide">START A BLANK MOLECULE</button></section>
          <label class="molecule-id"><span>PARENT ID</span><input id="parent-name" value="PARENT-001" autocomplete="off" spellcheck="false"></label>
          <div id="parent-depiction" class="parent-depiction"><div class="empty-parent"><i>◇</i><b>NO PARENT LOADED</b><span>Import a standard molecular format. The original remains immutable.</span></div></div>
          <div class="parent-contract"><span><small>FORMAT</small><b id="parent-format">—</b></span><span><small>CANONICAL IDENTITY</small><b id="parent-canonical">—</b></span><span><small>GRAPH</small><b id="parent-graph">—</b></span></div>
        </aside>
        <main class="proposal-workspace"><div class="editor-pane-head"><span><small>EDITABLE COPY</small><b>PROPOSAL MOLECULE</b></span><em id="proposal-state">AWAITING PARENT</em></div>
          <div class="sketch-name"><label><span>PROPOSAL ID</span><input id="sketch-name" value="PROPOSAL-001" autocomplete="off" spellcheck="false"></label><div><b id="sketch-formula">0 ATOMS · 0 BONDS</b><span id="sketch-smiles">NOT VALIDATED</span></div></div>
          <svg id="sketch-canvas" viewBox="0 0 840 520" role="application" aria-label="Editable two-dimensional proposal molecular graph"><defs><pattern id="sketch-grid" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M 24 0 L 0 0 0 24" fill="none" stroke="#0b2730" stroke-width="1"/></pattern></defs><rect class="sketch-bg" width="840" height="520" fill="url(#sketch-grid)"/></svg>
          <div class="sketch-status"><span id="sketch-status">${this.status}</span><em>CLICK ATOM OR BOND · DRAG ATOM TO MOVE</em></div>
          <div class="change-strip"><span><small>ATOMS</small><b id="delta-atoms">—</b></span><span><small>BONDS</small><b id="delta-bonds">—</b></span><span><small>IDENTITY</small><b id="identity-state">NO PARENT</b></span><span><small>VALIDATION</small><b id="chemistry-state">AWAITING GRAPH</b></span></div>
        </main>
        <aside class="operation-workspace"><div class="editor-pane-head"><span><small>SELECT THEN ACT</small><b>TRANSFORMATION TOOLS</b></span><em>LOCAL</em></div>
          <section><b>REPLACE SELECTED ATOM</b><div class="atom-tools">${(['C','N','O','S','F','Cl','Br'] as ElementSymbol[]).map((e,i)=>`<button data-element="${e}" class="${i===0?'active':''}">${e}</button>`).join('')}</div><small>Click an atom in Proposal, then choose the replacement element.</small></section>
          <section><b>CHANGE SELECTED BOND</b><div class="bond-tools"><button data-bond="1" class="active">—</button><button data-bond="2">═</button><button data-bond="3">≡</button></div><small>Click a bond in Proposal, then choose its order.</small></section>
          <section><b>DELETE</b><div class="delete-tools"><button id="delete-branch">DELETE SMALLER BRANCH</button><button id="sketch-delete">DELETE ATOM</button></div><small>Branch deletion cuts the selected bond and removes its smaller connected side.</small></section>
          <section><b>ATTACH AT SELECTED ATOM</b><button id="attach-carbon" class="wide">＋ CARBON</button><button id="add-benzene" class="wide">＋ PHENYL</button><button id="add-cyclopropyl" class="wide">＋ CYCLOPROPYL</button><small>Select an attachment atom first. New fragments remain fully editable.</small></section>
          <section class="edit-tools"><b>HISTORY</b><div><button id="sketch-undo">UNDO</button><button id="sketch-redo">REDO</button></div><div><button id="reset-proposal">RESET TO REFERENCE</button><button id="sketch-clear">CLEAR CANVAS</button></div></section>
          <section class="selection-evidence"><small>CURRENT SELECTION</small><b id="current-selection">NONE</b><span id="selection-instruction">Select an atom or bond in the Proposal canvas.</span></section>
        </aside>
      </div>
      <footer><div><button id="sketch-validate">VALIDATE MOLECULE</button><button id="sketch-new">NEW MOLECULE</button></div><span><b>REFERENCE IS NEVER OVERWRITTEN</b><small>With a reference, saving can add both identities; blank mode adds the new molecule only.</small></span><button id="sketch-add" class="primary" disabled>ADD MOLECULE TO SERIES →</button></footer>
    </div>`;
}

    private bind():void {
        this.host.querySelector('#sketch-close')?.addEventListener('click',()=>this.close()); this.host.querySelector('#load-parent-smiles')?.addEventListener('click',()=>void this.loadParent(this.host.querySelector<HTMLInputElement>('#parent-smiles')!.value,'SMILES')); this.host.querySelector('#start-blank')?.addEventListener('click',()=>this.startBlank());
        this.host.querySelector<HTMLInputElement>('#parent-smiles')?.addEventListener('keydown',e=>{ if (e.key==='Enter') void this.loadParent((e.currentTarget as HTMLInputElement).value,'SMILES'); }); this.host.querySelector<HTMLInputElement>('#parent-file')?.addEventListener('change',e=>{ const file=(e.currentTarget as HTMLInputElement).files?.[0]; if (file) void file.text().then((content:string)=>this.loadParent(content.split('$$$$')[0],file.name.toUpperCase())); });
        this.host.querySelectorAll<HTMLButtonElement>('[data-element]').forEach(b=>b.addEventListener('click',()=>this.replaceOrSetElement(b))); this.host.querySelectorAll<HTMLButtonElement>('[data-bond]').forEach(b=>b.addEventListener('click',()=>this.changeOrSetBond(b)));
        this.host.querySelector('#delete-branch')?.addEventListener('click',()=>this.deleteBranch()); this.host.querySelector('#sketch-delete')?.addEventListener('click',()=>this.deleteSelectedAtom()); this.host.querySelector('#attach-carbon')?.addEventListener('click',()=>this.attachAtom('C')); this.host.querySelector('#add-benzene')?.addEventListener('click',()=>this.addRing(6,true)); this.host.querySelector('#add-cyclopropyl')?.addEventListener('click',()=>this.addRing(3,false));
        this.host.querySelector('#sketch-clear')?.addEventListener('click',()=>this.clearProposal()); this.host.querySelector('#reset-proposal')?.addEventListener('click',()=>this.resetToParent()); this.host.querySelector('#sketch-new')?.addEventListener('click',()=>this.nextProposal()); this.host.querySelector('#sketch-undo')?.addEventListener('click',()=>this.undo()); this.host.querySelector('#sketch-redo')?.addEventListener('click',()=>this.redo()); this.host.querySelector('#sketch-validate')?.addEventListener('click',()=>void this.validate()); this.host.querySelector('#sketch-add')?.addEventListener('click',()=>void this.addPair());
        const svg=this.host.querySelector<SVGSVGElement>('#sketch-canvas')!; svg.addEventListener('pointerdown',e=>this.pointerDown(e)); svg.addEventListener('pointermove',e=>this.pointerMove(e)); svg.addEventListener('pointerup',e=>this.pointerUp(e)); svg.addEventListener('pointerleave',e=>this.pointerUp(e));
    }

    private async loadParent(input:string,format:string):Promise<void> {
        if (!input.trim()) { this.setStatus('PASTE SMILES OR SELECT A MOL / SDF FILE'); return; } this.setStatus('RDKIT IS PARSING THE PARENT GRAPH…');
        try { const RDKit=await getRDKit(),mol=RDKit.get_mol(input.trim()); if (!mol||!mol.is_valid()) throw new Error('RDKit could not parse this molecular record.'); try { try { mol.set_new_coords(true); } catch {} const molblock=mol.get_molblock(),smiles=mol.get_smiles(),graph=parseMolblock(molblock),id=this.host.querySelector<HTMLInputElement>('#parent-name')!.value.trim()||'PARENT-001'; this.parent={ id,smiles,molblock,atomCount: graph.atoms.length }; this.parentGraph=graph; this.restore({ atoms: graph.atoms,bonds: graph.bonds,selectedAtom: null,selectedBond: null }); this.history=[]; this.future=[]; this.text('parent-format',format); this.text('parent-canonical',smiles); this.text('parent-graph',`${graph.atoms.length} ATOMS · ${graph.bonds.length} BONDS`); this.text('proposal-state','EDITABLE COPY'); this.setStatus('PARENT IMPORTED · SELECT AN ATOM OR BOND TO CREATE A PROPOSAL'); const depiction=await LigandDepiction.depict(molblock,{ width: 620,height: 450 }),host=this.host.querySelector('#parent-depiction'); if (host)host.innerHTML=depiction?.svgString||'<div class="empty-parent"><b>2D DEPICTION UNAVAILABLE</b></div>'; } finally { mol.delete(); } } catch (error) { this.setStatus(`PARENT IMPORT FAILED · ${error instanceof Error?error.message:String(error)}`); }
    }

    private replaceOrSetElement(button:HTMLButtonElement):void { this.element=button.dataset.element as ElementSymbol; this.host.querySelectorAll('[data-element]').forEach(i=>i.classList.toggle('active',i===button)); if (this.selectedAtom==null) { this.setStatus(`INSERTION ELEMENT SET TO ${this.element}`); return; } this.pushHistory(); const atom=this.atom(this.selectedAtom); if (atom)atom.element=this.element; this.setStatus(`ATOM ${this.selectedAtom} REPLACED WITH ${this.element}`); this.render(); }
    private changeOrSetBond(button:HTMLButtonElement):void { this.bondOrder=Number(button.dataset.bond) as BondOrder; this.host.querySelectorAll('[data-bond]').forEach(i=>i.classList.toggle('active',i===button)); if (this.selectedBond==null) { this.setStatus(`INSERTION BOND SET TO ORDER ${this.bondOrder}`); return; } this.pushHistory(); const bond=this.bonds.find(b=>b.id===this.selectedBond); if (bond)bond.order=this.bondOrder; this.setStatus(`BOND ${this.selectedBond} CHANGED TO ORDER ${this.bondOrder}`); this.render(); }
    private point(e:PointerEvent):{x:number;y:number} { const svg=this.host.querySelector<SVGSVGElement>('#sketch-canvas')!,r=svg.getBoundingClientRect(); return { x: Math.max(26,Math.min(814,(e.clientX-r.left)/r.width*840)),y: Math.max(26,Math.min(494,(e.clientY-r.top)/r.height*520)) }; }
    private pointerDown(e:PointerEvent):void { const id=Number((e.target as Element).closest('[data-atom-id]')?.getAttribute('data-atom-id')); if (id) { this.dragAtom=id; this.dragMoved=false; (e.currentTarget as SVGSVGElement).setPointerCapture?.(e.pointerId); } }
    private pointerMove(e:PointerEvent):void { if (this.dragAtom==null||!(e.buttons&1)) return; const atom=this.atom(this.dragAtom); if (!atom) return; if (!this.dragMoved) this.pushHistory(); const p=this.point(e); atom.x=p.x; atom.y=p.y; this.dragMoved=true; this.render(); }
    private pointerUp(e:PointerEvent):void { const target=e.target as Element; if (this.dragAtom!=null) { const id=this.dragAtom; this.dragAtom=null; if (this.dragMoved) { this.setStatus(`ATOM ${id} MOVED`); this.render(); return; } this.selectAtom(id); return; } const bondId=Number(target.closest('[data-bond-id]')?.getAttribute('data-bond-id')); if (bondId) { this.selectedBond=bondId; this.selectedAtom=null; this.setStatus(`BOND ${bondId} SELECTED · CHANGE ORDER OR DELETE A BRANCH`); this.render(); return; } if (target.classList.contains('sketch-bg')) this.clickCanvas(this.point(e)); }
    private selectAtom(id:number):void { if (this.selectedAtom===id) { this.selectedAtom=null; this.setStatus('SELECTION CLEARED'); } else { this.selectedAtom=id; this.selectedBond=null; this.setStatus(`ATOM ${id} SELECTED · REPLACE, DELETE, OR ATTACH A FRAGMENT`); } this.render(); }
    private clickCanvas(p:{x:number;y:number}):void { this.pushHistory(); const atom={ id: this.nextAtomId++,element: this.element,...p }; this.atoms.push(atom); if (this.selectedAtom!=null) this.upsertBond(this.selectedAtom,atom.id,this.bondOrder); this.selectedAtom=atom.id; this.selectedBond=null; this.setStatus(`PLACED ${this.element} · ATOM ${atom.id} SELECTED`); this.render(); }
    private availableDirection(id:number):number { const c=this.atom(id)!,neighbors=this.bonds.filter(b=>b.a===id||b.b===id).map(b=>this.atom(b.a===id?b.b:b.a)!).filter(Boolean); if (!neighbors.length) return 0; const vx=neighbors.reduce((s,a)=>s+a.x-c.x,0),vy=neighbors.reduce((s,a)=>s+a.y-c.y,0); return Math.atan2(-vy,-vx); }
    private attachAtom(element:ElementSymbol):void { if (this.selectedAtom==null) { this.setStatus('SELECT AN ATTACHMENT ATOM FIRST'); return; } const parent=this.atom(this.selectedAtom); if (!parent) return; this.pushHistory(); const angle=this.availableDirection(parent.id),atom={ id: this.nextAtomId++,element,x: parent.x+Math.cos(angle)*82,y: parent.y+Math.sin(angle)*82 }; this.atoms.push(atom); this.upsertBond(parent.id,atom.id,this.bondOrder); this.selectedAtom=atom.id; this.setStatus(`${element} ATTACHED · NEW ATOM ${atom.id} SELECTED`); this.render(); }
    private addRing(size:3|6,aromatic:boolean):void { if (this.selectedAtom==null) { this.setStatus('SELECT AN ATTACHMENT ATOM BEFORE ADDING A FRAGMENT'); return; } const anchor=this.atom(this.selectedAtom); if (!anchor) return; this.pushHistory(); const angle=this.availableDirection(anchor.id),center={ x: anchor.x+Math.cos(angle)*(size===6?150:120),y: anchor.y+Math.sin(angle)*(size===6?150:120) },radius=size===6?70:52,ids:number[]=[]; for (let i=0; i<size; i++) { const theta=angle+Math.PI+i*Math.PI*2/size,atom={ id: this.nextAtomId++,element: 'C' as ElementSymbol,x: center.x+Math.cos(theta)*radius,y: center.y+Math.sin(theta)*radius }; this.atoms.push(atom); ids.push(atom.id); } for (let i=0; i<size; i++) this.upsertBond(ids[i],ids[(i+1)%size],aromatic&&i%2===0?2:1); this.upsertBond(anchor.id,ids[0],1); this.selectedAtom=ids[0]; this.setStatus(`${aromatic?'PHENYL':'CYCLOPROPYL'} ATTACHED · ALL NEW ATOMS EDITABLE`); this.render(); }
    private deleteSelectedAtom():void { if (this.selectedAtom==null) { this.setStatus('SELECT AN ATOM TO DELETE'); return; } this.pushHistory(); const id=this.selectedAtom; this.atoms=this.atoms.filter(a=>a.id!==id); this.bonds=this.bonds.filter(b=>b.a!==id&&b.b!==id); this.selectedAtom=null; this.setStatus(`ATOM ${id} AND INCIDENT BONDS DELETED`); this.render(); }
    private deleteBranch():void { const bond=this.bonds.find(b=>b.id===this.selectedBond); if (!bond) { this.setStatus('SELECT THE BOND THAT DEFINES THE BRANCH'); return; } const component=(start:number)=>{ const seen=new Set<number>([start]),stack=[start]; while (stack.length) { const current=stack.pop()!; for (const item of this.bonds) { if (item.id===bond.id) continue; const next=item.a===current?item.b:item.b===current?item.a:null; if (next!=null&&!seen.has(next)) { seen.add(next); stack.push(next); } } } return seen; },left=component(bond.a),right=component(bond.b); if (left.size+right.size!==this.atoms.length) { this.setStatus('THIS BOND IS IN A RING · BRANCH DELETION REFUSED'); return; } const remove=left.size<right.size?left:right; this.pushHistory(); this.atoms=this.atoms.filter(a=>!remove.has(a.id)); this.bonds=this.bonds.filter(b=>!remove.has(b.a)&&!remove.has(b.b)); this.selectedBond=null; this.setStatus(`BRANCH DELETED · ${remove.size} ATOM${remove.size===1?'':'S'} REMOVED`); this.render(); }
    private upsertBond(a:number,b:number,order:BondOrder):void { const existing=this.bonds.find(x=>(x.a===a&&x.b===b)||(x.a===b&&x.b===a)); if (existing)existing.order=order; else this.bonds.push({ id: this.nextBondId++,a,b,order }); }
    private atom(id:number):SketchAtom|undefined { return this.atoms.find(a=>a.id===id); }
    private pushHistory():void { this.history.push(cloneState({ atoms: this.atoms,bonds: this.bonds,selectedAtom: this.selectedAtom,selectedBond: this.selectedBond })); this.future=[]; }
    private restore(s:SketchState):void { this.atoms=s.atoms.map(a=>({ ...a })); this.bonds=s.bonds.map(b=>({ ...b })); this.selectedAtom=s.selectedAtom; this.selectedBond=s.selectedBond; this.nextAtomId=Math.max(0,...this.atoms.map(a=>a.id))+1; this.nextBondId=Math.max(0,...this.bonds.map(b=>b.id))+1; this.render(); }
    private undo():void { const s=this.history.pop(); if (!s) return; this.future.push(cloneState({ atoms: this.atoms,bonds: this.bonds,selectedAtom: this.selectedAtom,selectedBond: this.selectedBond })); this.restore(s); this.setStatus('UNDO'); }
    private redo():void { const s=this.future.pop(); if (!s) return; this.history.push(cloneState({ atoms: this.atoms,bonds: this.bonds,selectedAtom: this.selectedAtom,selectedBond: this.selectedBond })); this.restore(s); this.setStatus('REDO'); }
    private resetToParent():void { if (!this.parentGraph) { this.setStatus('IMPORT A PARENT FIRST'); return; } this.pushHistory(); this.restore({ atoms: this.parentGraph.atoms,bonds: this.parentGraph.bonds,selectedAtom: null,selectedBond: null }); this.setStatus('PROPOSAL RESET TO IMMUTABLE PARENT'); }
    private clearProposal():void { this.pushHistory(); this.restore({ atoms: [],bonds: [],selectedAtom: null,selectedBond: null }); this.setStatus('BLANK ADVANCED MODE · PARENT REMAINS IMMUTABLE'); }
    private startBlank():void { this.parent=null; this.parentGraph=null; this.history=[]; this.future=[]; this.restore({ atoms: [],bonds: [],selectedAtom: null,selectedBond: null }); this.text('parent-format','BLANK'); this.text('parent-canonical','—'); this.text('parent-graph','—'); const host=this.host.querySelector('#parent-depiction'); if (host)host.innerHTML='<div class="empty-parent"><i>＋</i><b>BLANK MODE</b><span>Click the proposal canvas to place the first atom.</span></div>'; this.setStatus('BLANK MODE · CLICK THE CANVAS TO PLACE THE FIRST CARBON'); }
    private nextProposal():void { if (this.parentGraph)this.resetToParent(); else this.clearProposal(); const input=this.host.querySelector<HTMLInputElement>('#sketch-name'); if (input) { const m=input.value.match(/^(.*?)(\d+)$/); input.value=m?`${m[1]}${String(Number(m[2])+1).padStart(m[2].length,'0')}`:'PROPOSAL-001'; } }
    private async validate():Promise<SketchedMolecule|null> { if (!this.atoms.length) { this.setStatus('EMPTY MOLECULE · IMPORT OR DRAW FIRST'); return null; } const id=this.host.querySelector<HTMLInputElement>('#sketch-name')?.value.trim()||'PROPOSAL-001',molblock=writeMolblock(id,this.atoms,this.bonds); try { const RDKit=await getRDKit(),mol=RDKit.get_mol(molblock); if (!mol||!mol.is_valid()) throw new Error('invalid valence, bond order, or disconnected graph'); try { const smiles=mol.get_smiles(); this.text('sketch-smiles',smiles); this.text('chemistry-state','VALID · CANONICALIZED'); this.text('proposal-state','VALID MOLECULE'); const add=this.host.querySelector<HTMLButtonElement>('#sketch-add'); if (add)add.disabled=false; this.setStatus(`RDKIT VALID · ${smiles}`); return { id,smiles,molblock,atomCount: this.atoms.length }; } finally { mol.delete(); } } catch (error) { this.text('chemistry-state','INVALID · EDIT REQUIRED'); const add=this.host.querySelector<HTMLButtonElement>('#sketch-add'); if (add)add.disabled=true; this.setStatus(`RDKIT REFUSED MOLECULE · ${error instanceof Error?error.message:String(error)}`); return null; } }
    private async addPair():Promise<void> { const proposal=await this.validate(); if (!proposal) return; if (this.parent) { const parentId=this.host.querySelector<HTMLInputElement>('#parent-name')!.value.trim()||this.parent.id; this.onAdd({ ...this.parent,id: parentId }); this.setStatus(`${parentId} + ${proposal.id} ADDED · READY FOR ANOTHER MOLECULE`); } else this.setStatus(`${proposal.id} ADDED · READY FOR ANOTHER MOLECULE`); this.onAdd(proposal); this.nextProposal(); }
    private render():void { const svg=this.host.querySelector<SVGSVGElement>('#sketch-canvas'); if (!svg) return; svg.querySelectorAll('.sketch-content').forEach(n=>n.remove()); const group=document.createElementNS('http://www.w3.org/2000/svg','g'); group.setAttribute('class','sketch-content'); group.setAttribute('stroke','#b9ced3'); group.setAttribute('stroke-linecap','round'); group.innerHTML=this.bonds.map(b=>{ const a=this.atom(b.a),c=this.atom(b.b); return a&&c?`<g data-bond-id="${b.id}" class="sketch-bond${b.id===this.selectedBond?' selected':''}">${bondLines(a,c,b.order)}<title>Bond ${b.id} · order ${b.order}</title></g>`:''; }).join('')+this.atoms.map(a=>`<g data-atom-id="${a.id}" class="sketch-atom${a.id===this.selectedAtom?' selected':''}" transform="translate(${a.x} ${a.y})"><circle r="${a.id===this.selectedAtom?16:13}"/><text text-anchor="middle" dominant-baseline="central">${escapeHtml(a.element==='C'?'':a.element)}</text><title>Atom ${a.id} · ${a.element}</title></g>`).join(''); svg.append(group); this.text('sketch-formula',`${this.atoms.length} ATOMS · ${this.bonds.length} BONDS`); this.text('delta-atoms',this.parentGraph?`${this.atoms.length-this.parentGraph.atoms.length>=0?'+':''}${this.atoms.length-this.parentGraph.atoms.length}`:'—'); this.text('delta-bonds',this.parentGraph?`${this.bonds.length-this.parentGraph.bonds.length>=0?'+':''}${this.bonds.length-this.parentGraph.bonds.length}`:'—'); this.text('identity-state',this.parentGraph?(this.graphMatchesParent()?'UNCHANGED':'MODIFIED'):'NEW MOLECULE'); this.text('current-selection',this.selectedAtom!=null?`ATOM ${this.selectedAtom} · ${this.atom(this.selectedAtom)?.element}`:this.selectedBond!=null?`BOND ${this.selectedBond}`:'NONE'); this.text('selection-instruction',this.selectedAtom!=null?'Replace, delete, or attach a fragment.':this.selectedBond!=null?'Change bond order or delete the smaller branch.':'Click the canvas to place an atom, or select an existing atom or bond.'); const undo=this.host.querySelector<HTMLButtonElement>('#sketch-undo'); if (undo)undo.disabled=!this.history.length; const redo=this.host.querySelector<HTMLButtonElement>('#sketch-redo'); if (redo)redo.disabled=!this.future.length; const add=this.host.querySelector<HTMLButtonElement>('#sketch-add'); if (add)add.disabled=true; this.text('chemistry-state',this.atoms.length?'CHANGED · VALIDATE':'AWAITING GRAPH'); this.text('proposal-state',this.parent?'EDITABLE COPY':'BLANK MODE'); if (add)add.textContent=this.parent?'ADD REFERENCE + MOLECULE TO SERIES →':'ADD MOLECULE TO SERIES →'; this.renderStatus(); }
    private graphMatchesParent():boolean { return !!this.parentGraph&&this.atoms.length===this.parentGraph.atoms.length&&this.bonds.length===this.parentGraph.bonds.length&&this.atoms.every((a,i)=>a.element===this.parentGraph!.atoms[i]?.element)&&this.bonds.every((b,i)=>b.order===this.parentGraph!.bonds[i]?.order); }
    private text(id:string,value:string):void { const node=this.host.querySelector(`#${id}`); if (node)node.textContent=value; }
    private setStatus(value:string):void { this.status=value; this.renderStatus(); }
    private renderStatus():void { this.text('sketch-status',this.status); }
}
