import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { escapeHtml } from './workbench-dom';

type Ref={id:string;sha256?:string};
type PairWitness=Record<string,unknown>;
type PolicyEvidenceRow={axis:string;verdict:'CONFIRMED'|'UNVERIFIED'|'OVERTURNED';witness:string};
export type ReviewPose={
    pose_ref:{id:string;sha256?:string};label:string;canonical_smiles:string;
    coordinate_artifact_ref?:Ref;core_rmsd_angstrom?:number;core_coverage?:number;
    minimum_heavy_atom_distance_angstrom?:number;protein_contacts_within_6_angstrom?:number;
    nearest_pair_witness?:PairWitness;contact_pair_witnesses?:PairWitness[];clash_pair_witnesses?:PairWitness[];
    metal_coordination_witnesses?:PairWitness[];cofactor_contact_witnesses?:PairWitness[];water_contact_witnesses?:PairWitness[];
    contact_pair_total?:number;contact_pairs_truncated?:boolean;pose_report?:Record<string,unknown>;geometry_evidence?:Record<string,unknown>;
};
export type ReviewSystem={
    label:string;parent_id:string;coordinate_artifact_ref?:Ref;poses:ReviewPose[];
    prepared_receptor_state_ref:Ref;
    receptor_report?:{policy_execution?:Record<string,{verdict?:string;observed_action?:unknown;witness?:unknown;witnesses?:unknown;reason?:unknown;details?:unknown}>};
};
type Atom={xyz:THREE.Vector3;element:string;residue?:string;atomName?:string;entity:'protein'|'water'|'metal'|'cofactor'};
type Molecule={atoms:Atom[];bonds:Array<[number,number,number]>};

const atomColour:Record<string,number>={ C: 0x9fb4bb,N: 0x4a83ff,O: 0xff5f6d,S: 0xf0c54b,P: 0xd989ff,F: 0x72efad,Cl: 0x55d68d,Br: 0xb9795f,I: 0x9d6ae8,H: 0xeaf4f5 };
const atomRadius:Record<string,number>={ C: .28,N: .3,O: .3,S: .36,P: .36,F: .3,Cl: .38,Br: .42,I: .46,H: .14 };
const metalElements=new Set(['LI','NA','K','RB','CS','MG','CA','SR','BA','MN','FE','CO','NI','CU','ZN','CD','HG']);
const waterResidues=new Set(['HOH','WAT','DOD']);
function normalElement(raw:string):string { const value=raw.trim(); return value.length>1?value[0].toUpperCase()+value.slice(1).toLowerCase():value.toUpperCase(); }

function parsePdb(text:string):Atom[] {
    const atoms:Atom[]=[];
    text.split(/\r?\n/).forEach(line=>{ const isProtein=line.startsWith('ATOM  '),isHetero=line.startsWith('HETATM'); if ((!isProtein&&!isHetero)||line.length<54) return; const rawElement=(line.length>=78?line.slice(76,78):line.slice(12,14)).trim().toUpperCase(); if (['H','D'].includes(rawElement)) return; const x=Number(line.slice(30,38)),y=Number(line.slice(38,46)),z=Number(line.slice(46,54)); if (![x,y,z].every(Number.isFinite)) return; const resname=line.slice(17,20).trim().toUpperCase(),entity:Atom['entity']=isProtein?'protein':waterResidues.has(resname)?'water':metalElements.has(rawElement)?'metal':'cofactor'; atoms.push({ xyz: new THREE.Vector3(x,y,z),element: normalElement(rawElement||'C'),atomName: line.slice(12,16).trim(),entity,residue: `${resname} ${line.slice(21,22).trim()}${line.slice(22,27).trim()}` }); });
    return atoms;
}
function parseSdf(text:string):Molecule {
    const lines=text.split(/\r?\n/),counts=lines[3]||'',atomCount=Number.parseInt(counts.slice(0,3).trim(),10),bondCount=Number.parseInt(counts.slice(3,6).trim(),10);
    if (!Number.isFinite(atomCount)||atomCount<1) throw new Error('Pose artifact has no readable atoms');
    const atoms=Array.from({ length: atomCount },(_,index)=>{ const line=lines[4+index]||''; return { xyz: new THREE.Vector3(Number(line.slice(0,10)),Number(line.slice(10,20)),Number(line.slice(20,30))),element: normalElement(line.slice(31,34).trim()||'C'),entity: 'cofactor' as const }; });
    const bonds=Array.from({ length: bondCount },(_,index)=>{ const line=lines[4+atomCount+index]||''; return [Number.parseInt(line.slice(0,3).trim(),10)-1,Number.parseInt(line.slice(3,6).trim(),10)-1,Number.parseInt(line.slice(6,9).trim(),10)||1] as [number,number,number]; }).filter(([a,b])=>a>=0&&b>=0&&a<atoms.length&&b<atoms.length);
    return { atoms,bonds };
}
function line(a:THREE.Vector3,b:THREE.Vector3,colour:number,opacity=1):THREE.Line {
    return new THREE.Line(new THREE.BufferGeometry().setFromPoints([a,b]),new THREE.LineBasicMaterial({ color: colour,transparent: opacity<1,opacity }));
}
function moleculeGroup(molecule:Molecule,opacity=1,bondTint?:number,atomTint?:number):THREE.Group {
    const group=new THREE.Group();
    molecule.bonds.forEach(([a,b,order])=>{ const first=molecule.atoms[a],second=molecule.atoms[b]; for (let i=0; i<Math.min(order,2); i++) { const offset=i?new THREE.Vector3(.05,.05,.05):new THREE.Vector3(); group.add(line(first.xyz.clone().add(offset),second.xyz.clone().add(offset),bondTint??0xc9d7da,opacity)); } });
    molecule.atoms.forEach(atom=>{ if (atom.element.toUpperCase()==='H') return; const geometry=new THREE.SphereGeometry(atomRadius[atom.element]||.3,16,12),material=new THREE.MeshStandardMaterial({ color: atomTint??atomColour[atom.element]??0xb8c8cc,roughness: .28,metalness: .05,transparent: opacity<1,opacity,depthWrite: opacity>=1 }); const mesh=new THREE.Mesh(geometry,material); mesh.position.copy(atom.xyz); group.add(mesh); });
    return group;
}
function residueLabel(label:string,position:THREE.Vector3):THREE.Sprite {
    const canvas=document.createElement('canvas'); canvas.width=256; canvas.height=64; const context=canvas.getContext('2d')!; context.font='700 25px monospace'; context.textAlign='center'; context.textBaseline='middle'; context.fillStyle='rgba(3,13,18,.85)'; context.fillRect(0,0,256,64); context.strokeStyle='#3b8b9c'; context.strokeRect(1,1,254,62); context.fillStyle='#d9f5f8'; context.fillText(label,128,33); const sprite=new THREE.Sprite(new THREE.SpriteMaterial({ map: new THREE.CanvasTexture(canvas),transparent: true,depthTest: false })); sprite.position.copy(position); sprite.scale.set(3.2,.8,1); sprite.renderOrder=9; return sprite;
}

export class PoseReviewer {
    private renderer:THREE.WebGLRenderer|null=null; private scene=new THREE.Scene(); private camera=new THREE.PerspectiveCamera(33,1,.1,500); private controls:OrbitControls|null=null;
    private receptor:Atom[]=[]; private molecules:Molecule[]=[]; private system:ReviewSystem|null=null; private selected=0; private parentIndex=0; private viewed=new Set<number>(); private animation=0; private accepted=false; private returnFocus:HTMLElement|null=null;
    constructor(private host:HTMLElement,private apiBase:string,private onAccept:(system:ReviewSystem)=>Promise<void>) {
        host.tabIndex=-1; host.innerHTML=`<header><button id="pose-review-back">← BACK TO BUILD</button><span><small>NEW CAMPAIGN · SCIENTIFIC REVIEW</small><b id="pose-review-title">REVIEW RECEPTOR-FRAME POSES</b></span><em>SAME CAMERA · NO AUTO-ROTATION</em></header><main><aside><div class="pose-review-question"><small>QUESTION 1</small><b>Does every analogue preserve the intended crystal-core orientation?</b><span>Open every pose. The receptor frame and camera never change between molecules.</span></div><div class="pose-policy-audit"><header><b>PREPARATION POLICY</b><em id="pose-policy-summary">UNVERIFIED</em></header><div id="pose-policy-rows"></div></div><div id="pose-review-list" class="pose-review-list"></div></aside><section class="pose-stage"><canvas></canvas><div class="pose-webgl-fallback" role="status" hidden><b>3D VIEW UNAVAILABLE</b><span>Use the tabular pose metrics. Acceptance stays blocked for hard clashes or missing evidence.</span></div><div class="pose-stage-legend"><span class="parent">PARENT OVERLAY</span><span class="proposal">SELECTED POSE</span><span class="contact">CONTACTS ≤ 3.5 Å · CLIENT VIEW</span></div><div class="pose-camera-help">DRAG ROTATE · WHEEL ZOOM · RIGHT-DRAG PAN</div></section><aside class="pose-review-evidence"><div><small>SELECTED POSE · FULL ID</small><b id="pose-review-name">—</b><span id="pose-review-method">REFERENCE-CONSTRAINED</span></div><dl><div><dt>Crystal-core RMSD</dt><dd id="pose-review-rmsd">—</dd></div><div><dt>Shared-core coverage</dt><dd id="pose-review-coverage">—</dd></div><div><dt>Closest protein atom</dt><dd id="pose-review-distance">—</dd></div><div><dt>Pocket contacts ≤ 6 Å</dt><dd id="pose-review-contacts">—</dd></div></dl><div class="pose-pair-evidence"><header><small>SERVER ATOM-PAIR EVIDENCE</small><b id="pose-pair-summary">UNVERIFIED</b></header><div id="pose-pair-witnesses"></div></div><div class="pose-contact-residues"><small>CLIENT-VIEW CLOSEST RESIDUES</small><b id="pose-review-residues">—</b></div><div class="pose-review-checks"><small>QUESTIONS 2–4 · HUMAN ATTESTATION</small><label><input type="checkbox" data-review-check="shared_coordinate_frame">All poses remain in one receptor frame</label><label><input type="checkbox" data-review-check="core_alignment">The intended shared core orientation is credible</label><label><input type="checkbox" data-review-check="pocket_geometry">No visible clash or pocket escape is accepted</label></div><div class="pose-review-boundary"><b>WHAT THIS ACCEPTS</b><span>Pose hypotheses for OpenFE system construction. Human review cannot override an UNVERIFIED / OVERTURNED preparation axis or missing atom-pair witness. This is not an FEP result.</span></div></aside></main><footer><span><b id="pose-review-progress">0 / 0 POSES VIEWED</b><small>Inspect every row and every preparation axis before acceptance.</small></span><button id="pose-review-accept" disabled>ACCEPT REVIEWED POSES →</button></footer>`;
        this.camera.position.set(0,0,22);
        this.scene.add(new THREE.HemisphereLight(0xbfeeff,0x071116,1.45)); const key=new THREE.DirectionalLight(0xffffff,2.2); key.position.set(8,12,10); this.scene.add(key); const rim=new THREE.DirectionalLight(0x34d9ff,1.4); rim.position.set(-12,-6,-8); this.scene.add(rim);
        host.querySelector('#pose-review-back')?.addEventListener('click',()=>this.close()); host.querySelectorAll<HTMLInputElement>('[data-review-check]').forEach(input=>input.addEventListener('change',()=>this.updateGate())); host.querySelector('#pose-review-accept')?.addEventListener('click',()=>void this.accept()); host.addEventListener('keydown',event=>this.keydown(event)); host.addEventListener('cancel',event=>{ event.preventDefault(); this.close(); }); new ResizeObserver(()=>this.resize()).observe(host.querySelector('.pose-stage')!);
    }
    private ensureRenderer():boolean { if (this.renderer) return true; try { this.renderer=new THREE.WebGLRenderer({ canvas: this.host.querySelector('canvas')!,antialias: true,alpha: false,powerPreference: 'high-performance',preserveDrawingBuffer: true }); this.renderer.setPixelRatio(Math.min(devicePixelRatio,2)); this.renderer.setClearColor(0x02090d,1); this.renderer.outputColorSpace=THREE.SRGBColorSpace; this.controls=new OrbitControls(this.camera,this.renderer.domElement); this.controls.enableDamping=true; this.controls.autoRotate=false; this.controls.minDistance=3; this.controls.maxDistance=100; this.loop(); return true; } catch { const fallback=this.host.querySelector<HTMLElement>('.pose-webgl-fallback'); if (fallback)fallback.hidden=false; this.host.classList.add('webgl-failed'); return false; } }
    private async artifact(ref:Ref|undefined):Promise<string> { if (!ref?.id||!/^sha256:[0-9a-f]{64}$/.test(String(ref.sha256||''))) throw new Error('Coordinate artifact requires an exact id + sha256 reference'); const response=await fetch(`${this.apiBase}/v2/artifacts/${encodeURIComponent(ref.id)}`,{ cache: 'no-store' }); if (!response.ok) throw new Error(`Coordinate artifact ${ref.id} returned HTTP ${response.status}`); const bytes=await response.arrayBuffer(),actual=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(value=>value.toString(16).padStart(2,'0')).join(''); if (ref.sha256!==`sha256:${actual}`) throw new Error(`Coordinate artifact ${ref.id} failed SHA-256 verification`); return new TextDecoder().decode(bytes); }
    private policyEvidence():PolicyEvidenceRow[] {
        const source=this.system?.receptor_report?.policy_execution; if (!source||!Object.keys(source).length) return [{ axis: 'policy_execution',verdict: 'UNVERIFIED',witness: 'Backend returned no per-axis preparation evidence' }];
        return Object.entries(source).sort(([left],[right])=>left.localeCompare(right)).map(([axis,row])=>{ const raw=String(row?.verdict||'UNVERIFIED').toUpperCase(),verdict:'CONFIRMED'|'UNVERIFIED'|'OVERTURNED'=raw==='CONFIRMED'?'CONFIRMED':raw==='OVERTURNED'?'OVERTURNED':'UNVERIFIED',value=row?.witness??row?.witnesses??row?.observed_action??row?.reason??row?.details; let witness='NO WITNESS RETURNED'; if (value!=null) { if (typeof value==='string'||typeof value==='number'||typeof value==='boolean')witness=String(value); else try { witness=JSON.stringify(value); } catch { witness='WITNESS COULD NOT BE SERIALIZED'; } } return { axis,verdict,witness }; });
    }
    private policyBlockers():PolicyEvidenceRow[] { return this.policyEvidence().filter(row=>row.verdict!=='CONFIRMED'); }
    private renderPolicy():void { const rows=this.policyEvidence(),blockers=rows.filter(row=>row.verdict!=='CONFIRMED'),host=this.host.querySelector('#pose-policy-rows'); this.setText('pose-policy-summary',blockers.length?`${blockers.length} BLOCKING AXIS${blockers.length===1?'':'ES'}`:'ALL AXES CONFIRMED'); if (host)host.innerHTML=rows.map(row=>`<div class="${row.verdict.toLowerCase()}"><b>${escapeHtml(row.axis.replace(/_/g,' ').toUpperCase())}</b><em>${row.verdict}</em><span>${escapeHtml(row.witness)}</span></div>`).join(''); this.host.querySelector('.pose-policy-audit')?.classList.toggle('blocked',blockers.length>0); }
    private geometryRecord(pose:ReviewPose):Record<string,unknown> {
        const report=(pose.pose_report||{}) as Record<string,unknown>,nested=((report.pose_geometry_evidence||report.geometry_evidence||report.geometry||pose.geometry_evidence||{}) as Record<string,unknown>); return { ...report,...nested,...pose };
    }
    private pairEvidence(pose:ReviewPose):{nearest:PairWitness|null;rows:Array<{kind:string;witness:PairWitness}>;total:number;truncated:boolean} {
        const source=this.geometryRecord(pose),object=(value:unknown):PairWitness|null=>value&&typeof value==='object'&&!Array.isArray(value)?value as PairWitness:null,array=(...keys:string[]):PairWitness[]=>{ for (const key of keys) { const value=source[key]; if (Array.isArray(value)) return value.filter(item=>item&&typeof item==='object') as PairWitness[]; } return []; };
        const nearest=object(source.nearest_pair_witness),groups:Array<[string,PairWitness[]]>=[['CLASH',array('clash_pair_witnesses','clash_pairs')],['CONTACT',array('contact_pair_witnesses','contact_pairs')],['METAL',array('metal_coordination_witnesses','metal_contacts','metal_coordination')],['COFACTOR',array('cofactor_contact_witnesses','cofactor_contacts')],['WATER',array('water_contact_witnesses','water_contacts')]]; const seen=new Set<string>(),rows:Array<{kind:string;witness:PairWitness}>=[];
        const add=(kind:string,witness:PairWitness)=>{ let key=''; try { key=JSON.stringify(witness); } catch { key=String(rows.length); } if (seen.has(key)) return; seen.add(key); rows.push({ kind,witness }); }; if (nearest)add('NEAREST',nearest); groups.forEach(([kind,items])=>items.forEach(item=>add(kind,item)));
        const numeric=(...keys:string[]):number|undefined=>{ for (const key of keys) { const value=Number(source[key]); if (Number.isFinite(value)) return value; } return undefined; },total=numeric('contact_pair_total','total_contact_pairs','contact_total','heavy_atom_contacts_within_6_angstrom','protein_contacts_within_6_angstrom')??rows.length,truncated=Boolean(source.contact_pairs_truncated||source.truncated)||total>rows.length; return { nearest,rows,total,truncated };
    }
    private readablePair(kind:string,witness:PairWitness):{pair:string;metric:string;raw:string} {
        const ligandIndex=witness.ligand_atom_index??witness.ligand_index??witness.atom_index,ligandElement=witness.ligand_element??witness.element??'?',proteinAtom=witness.protein_atom_name??witness.receptor_atom_name??witness.atom_name??`ATOM ${String(witness.protein_atom_index??'?')}`,residue=[witness.residue_name,witness.chain_id,witness.residue_number].filter(value=>value!==undefined&&value!==null&&value!=='').join(' '),distance=Number(witness.distance_angstrom??witness.distance),hard=Number(witness.hard_clash_floor_angstrom),contact=Number(witness.contact_ceiling_angstrom),cutoffs=[Number.isFinite(hard)?`clash floor ${hard.toFixed(2)} Å`:'',Number.isFinite(contact)?`contact ceiling ${contact.toFixed(2)} Å`:''].filter(Boolean).join(' · '); let raw=''; try { raw=JSON.stringify(witness); } catch { raw='UNSERIALIZABLE WITNESS'; } return { pair: `LIG ${ligandElement}${ligandIndex!==undefined?`[${String(ligandIndex)}]`:''} ↔ ${residue?`${residue} · `:''}${String(proteinAtom)}`,metric: `${kind} · ${Number.isFinite(distance)?`${distance.toFixed(3)} Å`:'DISTANCE UNREPORTED'}${cutoffs?` · ${cutoffs}`:''}`,raw };
    }
    private renderPairEvidence(pose:ReviewPose):void { const evidence=this.pairEvidence(pose),host=this.host.querySelector('#pose-pair-witnesses'); this.setText('pose-pair-summary',evidence.nearest?`${evidence.rows.length} SHOWN / ${evidence.total} TOTAL${evidence.truncated?' · TRUNCATED':''}`:'UNVERIFIED · NEAREST PAIR MISSING'); if (host)host.innerHTML=evidence.rows.length?evidence.rows.map(row=>{ const readable=this.readablePair(row.kind,row.witness); return `<article><b>${escapeHtml(readable.pair)}</b><span>${escapeHtml(readable.metric)}</span><details><summary>RAW WITNESS</summary><code>${escapeHtml(readable.raw)}</code></details></article>`; }).join(''):'<p>SERVER RETURNED NO ATOM-PAIR WITNESS · HUMAN VISUAL REVIEW CANNOT SUBSTITUTE</p>'; }
    async open(system:ReviewSystem):Promise<void> { const parentMatches=system.poses.map((pose,index)=>pose.label===system.parent_id?index:-1).filter(index=>index>=0); if (!system.parent_id||parentMatches.length!==1) throw new Error(`Pose review requires one explicit parent_id match; received ${parentMatches.length}`); this.system=system; this.parentIndex=parentMatches[0]; this.accepted=false; this.selected=this.parentIndex; this.viewed.clear(); this.returnFocus=document.activeElement instanceof HTMLElement?document.activeElement:null; [...this.host.parentElement!.children].forEach(element=>{ if (element!==this.host)(element as HTMLElement).inert=true; }); if (this.host instanceof HTMLDialogElement&&!this.host.open) this.host.showModal(); this.host.classList.add('open'); this.host.setAttribute('aria-hidden','false'); this.renderPolicy(); this.ensureRenderer(); this.host.querySelector<HTMLButtonElement>('#pose-review-back')?.focus(); this.setStatus('VERIFYING CONTENT-ADDRESSED COORDINATES…'); try { const [pdb,...sdfs]=await Promise.all([this.artifact(system.coordinate_artifact_ref),...system.poses.map(pose=>this.artifact(pose.coordinate_artifact_ref))]); this.receptor=parsePdb(pdb); this.molecules=sdfs.map(parseSdf); this.renderList(); this.select(this.parentIndex,true); } catch (error) { this.setStatus(error instanceof Error?error.message:String(error)); } }
    close():void { this.host.classList.remove('open'); this.host.setAttribute('aria-hidden','true'); if (this.host instanceof HTMLDialogElement&&this.host.open) this.host.close(); [...this.host.parentElement!.children].forEach(element=>(element as HTMLElement).inert=false); this.returnFocus?.focus(); }
    private keydown(event:KeyboardEvent):void { if (event.key==='Escape') { event.preventDefault(); this.close(); return; } if (event.key!=='Tab') return; const focusable=[...this.host.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(element=>element.offsetParent!==null); if (!focusable.length) return; const first=focusable[0],last=focusable[focusable.length-1]; if (event.shiftKey&&document.activeElement===first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey&&document.activeElement===last) { event.preventDefault(); first.focus(); } }
    private setStatus(message:string):void { const target=this.host.querySelector('#pose-review-progress'); if (target)target.textContent=message; }
    private renderList():void { const list=this.host.querySelector('#pose-review-list'); if (!list||!this.system) return; list.innerHTML=this.system.poses.map((pose,index)=>{ const clash=Number.isFinite(pose.minimum_heavy_atom_distance_angstrom)&&Number(pose.minimum_heavy_atom_distance_angstrom)<1.5,missingWitness=!this.pairEvidence(pose).nearest; return `<button id="pose-row-${index}" data-pose-index="${index}" class="${clash?'hard-clash':missingWitness?'missing-witness':''}" title="${escapeHtml(pose.label)}"><i>${String(index+1).padStart(2,'0')}</i><span><b>${escapeHtml(pose.label)}</b><small>${index===this.parentIndex?'CRYSTALLOGRAPHIC PARENT':'REFERENCE-CONSTRAINED PROPOSAL'}</small></span><em>${clash?'HARD CLASH':missingWitness?'WITNESS MISSING':Number.isFinite(pose.core_coverage)?`${Math.round(Number(pose.core_coverage)*100)}% CORE`:'—'}</em></button>`; }).join(''); list.querySelectorAll<HTMLButtonElement>('button').forEach(button=>button.addEventListener('click',()=>this.select(Number(button.dataset.poseIndex)))); }
    private select(index:number,resetCamera=false):void { if (!this.system||!this.molecules[index]) return; this.selected=index; this.viewed.add(index); this.host.querySelectorAll('.pose-review-list button').forEach((button,row)=>button.classList.toggle('active',row===index)); const pose=this.system.poses[index]; this.setText('pose-review-name',pose.label); this.setText('pose-review-method',index===this.parentIndex?'MEASURED CRYSTAL COORDINATES':'ETKDG + MCS TETHER · REVIEW REQUIRED'); this.setText('pose-review-rmsd',Number.isFinite(pose.core_rmsd_angstrom)?`${Number(pose.core_rmsd_angstrom).toFixed(3)} Å`:'UNVERIFIED'); this.setText('pose-review-coverage',Number.isFinite(pose.core_coverage)?`${(Number(pose.core_coverage)*100).toFixed(0)}%`:'UNVERIFIED'); this.setText('pose-review-distance',Number.isFinite(pose.minimum_heavy_atom_distance_angstrom)?`${Number(pose.minimum_heavy_atom_distance_angstrom).toFixed(2)} Å`:'UNVERIFIED'); this.setText('pose-review-contacts',Number.isFinite(pose.protein_contacts_within_6_angstrom)?String(pose.protein_contacts_within_6_angstrom):'UNVERIFIED'); this.renderPairEvidence(pose); this.draw(resetCamera); this.updateGate(); }
    private setText(id:string,value:string):void { const target=this.host.querySelector(`#${id}`); if (target)target.textContent=value; }
    private draw(resetCamera:boolean):void {
const selected=this.molecules[this.selected],parent=this.molecules[this.parentIndex]; if (!selected||!parent) return; while (this.scene.children.length>3) this.scene.remove(this.scene.children[3]); if (this.selected!==this.parentIndex) this.scene.add(moleculeGroup(parent,.26,0x36dff3,0x36dff3)); this.scene.add(moleculeGroup(selected,1,this.selected===this.parentIndex?0x57e8fa:0xf0b84d)); const selectedHeavy=selected.atoms.filter(atom=>atom.element.toUpperCase()!=='H'); const pocket=this.receptor.filter(atom=>selectedHeavy.some(ligand=>atom.xyz.distanceTo(ligand.xyz)<=6)); const pocketGroup=new THREE.Group(); pocket.forEach(atom=>{ const minimum=Math.min(...selectedHeavy.map(ligand=>atom.xyz.distanceTo(ligand.xyz))); const mesh=new THREE.Mesh(new THREE.SphereGeometry(minimum<=3.5?.15:.1,10,8),new THREE.MeshStandardMaterial({ color: atomColour[atom.element]??0x73858c,transparent: true,opacity: minimum<=3.5?.7:.38,roughness: .5 })); mesh.position.copy(atom.xyz); pocketGroup.add(mesh); }); for (let i=0; i<pocket.length; i++) for (let j=i+1; j<pocket.length; j++) { const distance=pocket[i].xyz.distanceTo(pocket[j].xyz); if (distance>=.9&&distance<=1.95)pocketGroup.add(line(pocket[i].xyz,pocket[j].xyz,0x52656c,.36)); }
        const residues=new Map<string,{atoms:Atom[];distance:number;ligand:Atom;protein:Atom}>(); pocket.forEach(atom=>{ const ligand=selectedHeavy.reduce((best,row)=>atom.xyz.distanceTo(row.xyz)<atom.xyz.distanceTo(best.xyz)?row:best,selectedHeavy[0]),distance=atom.xyz.distanceTo(ligand.xyz),key=atom.residue||'UNK'; const row=residues.get(key); if (!row||distance<row.distance)residues.set(key,{ atoms: row?.atoms?[...row.atoms,atom]:[atom],distance,ligand,protein: atom }); else row.atoms.push(atom); }); const closest=[...residues.entries()].sort((a,b)=>a[1].distance-b[1].distance).slice(0,6); closest.forEach(([label,row],index)=>{ if (row.distance<=3.5)pocketGroup.add(line(row.protein.xyz,row.ligand.xyz,0x57e99a,.7)); const center=row.atoms.reduce((sum,atom)=>sum.add(atom.xyz),new THREE.Vector3()).multiplyScalar(1/row.atoms.length); center.y+=.45+index*.02; pocketGroup.add(residueLabel(label,center)); }); this.setText('pose-review-residues',closest.map(([label,row])=>`${label} ${row.distance.toFixed(1)} Å`).join(' · ')||'—'); this.scene.add(pocketGroup); if (resetCamera&&this.controls) { const box=new THREE.Box3().setFromObject(this.scene),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()).length(); this.controls.target.copy(center); this.camera.position.copy(center).add(new THREE.Vector3(0,0,Math.max(12,size*1.3))); this.camera.near=.1; this.camera.far=Math.max(200,size*10); this.camera.updateProjectionMatrix(); this.controls.update(); }
}
    private updateGate():void { if (!this.system) return; const hardClashes=this.system.poses.filter(pose=>Number.isFinite(pose.minimum_heavy_atom_distance_angstrom)&&Number(pose.minimum_heavy_atom_distance_angstrom)<1.5),missingWitnesses=this.system.poses.filter(pose=>!this.pairEvidence(pose).nearest),policyBlockers=this.policyBlockers(); if (policyBlockers.length) this.setStatus(`PREPARATION GATE · ${policyBlockers.length} UNRESOLVED / OVERTURNED AXIS${policyBlockers.length===1?'':'ES'} · ACCEPTANCE LOCKED`); else if (hardClashes.length) this.setStatus(`HARD GATE · ${hardClashes.length} POSE CLASH${hardClashes.length===1?'':'ES'} < 1.50 Å · ACCEPTANCE LOCKED`); else if (missingWitnesses.length) this.setStatus(`EVIDENCE GATE · ${missingWitnesses.length} POSE${missingWitnesses.length===1?'':'S'} LACK SERVER ATOM-PAIR WITNESS · ACCEPTANCE LOCKED`); else this.setStatus(`${this.viewed.size} / ${this.system.poses.length} POSES VIEWED`); const checks=[...this.host.querySelectorAll<HTMLInputElement>('[data-review-check]')].every(input=>input.checked),allViewed=this.viewed.size===this.system.poses.length; const button=this.host.querySelector<HTMLButtonElement>('#pose-review-accept'); if (button)button.disabled=!checks||!allViewed||!!hardClashes.length||!!missingWitnesses.length||!!policyBlockers.length||this.accepted; }
    private async accept():Promise<void> { if (!this.system) return; const button=this.host.querySelector<HTMLButtonElement>('#pose-review-accept'); if (!button) return; button.disabled=true; button.textContent='RECORDING REVIEW…'; try { await this.onAccept(this.system); this.accepted=true; button.textContent='POSES ACCEPTED ✓'; this.setStatus(`${this.system.poses.length} / ${this.system.poses.length} POSES REVIEWED · ACCEPTED`); setTimeout(()=>this.close(),650); } catch (error) { button.textContent='ACCEPT REVIEWED POSES →'; this.setStatus(`REVIEW REFUSED · ${error instanceof Error?error.message:String(error)}`); this.updateGate(); } }
    private resize():void { if (!this.renderer) return; const canvas=this.renderer.domElement,rect=canvas.getBoundingClientRect(); if (rect.width<1||rect.height<1) return; this.renderer.setSize(rect.width,rect.height,false); this.camera.aspect=rect.width/rect.height; this.camera.updateProjectionMatrix(); }
    private loop=():void=>{ this.animation=requestAnimationFrame(this.loop); if (!this.host.classList.contains('open')||!this.renderer||!this.controls) return; this.controls.update(); this.renderer.render(this.scene,this.camera); };
    dispose():void { cancelAnimationFrame(this.animation); this.controls?.dispose(); this.renderer?.dispose(); }
}
