import { WORKBENCH_ROUTES } from './workbench-routes';

/** Static workbench shell; controllers bind behavior after this mount. */
export function workbenchShellMarkup(): string {
    return `<div class="lab">
  <header class="topbar fep-topbar">
    <div class="fep-topbar-left"><div class="brand"><i></i><b>DIRAC</b><span>FEP QUALIFICATION LAB</span></div><div class="context"><span><small>DATASET</small><b>T4L PREPARED BENCHMARK</b></span><span><small>PLANNER</small><b>OPENFE 1.11.1</b></span><span><small>EDGE RESULTS</small><b class="result-zero" id="result-count">0 · NONE</b></span><span><small>BACKEND</small><b class="live" id="engine-state">● CONNECTING</b></span></div></div>
    <nav class="workspace-mode-tabs" aria-label="FEP workspace mode"><button id="main-build" aria-pressed="false">BUILD</button><button id="main-review" class="active" aria-pressed="true">REVIEW NETWORK</button><button id="main-runs" aria-pressed="false">RUNS</button></nav>
    <nav class="fep-topbar-actions"><a href="${WORKBENCH_ROUTES.allLabs}">ALL LABS</a><a href="${WORKBENCH_ROUTES.fieldWorkbench}">FIELD WORKBENCH</a><button id="replan" title="Re-run the currently displayed immutable network plan">REPLAN BENCHMARK</button></nav>
  </header>
  <div class="statusbar"><span><i></i>REAL OPENFE NETWORK PLAN</span><span class="dataset-scope">DATASET · T4 LYSOZYME TECHNICAL BENCHMARK</span><strong id="run-boundary">PLAN ONLY · 0 EDGE RESULTS</strong><em id="status" role="status" aria-live="polite">READING DURABLE JOB</em></div>
  <main class="workspace">
    <aside class="left-col">
      <section class="panel summary"><div class="head"><b>NETWORK CONTRACT</b><span>PLANNER OUTPUT</span></div><div class="summary-grid"><div><small>NODES</small><b id="node-count">—</b></div><div><small>EDGES</small><b id="edge-count">—</b></div><div><small>MAP SCORE ≥ .80</small><b class="good" id="ready-count">—</b></div><div><small>MAP SCORE &lt; .50</small><b class="bad" id="blocked-count">—</b></div></div><dl><div><dt>Target</dt><dd class="missing" id="target-state">NOT SUPPLIED</dd></div><div><dt>Protein / pose</dt><dd class="missing" id="pose-state">NOT SUPPLIED</dd></div><div><dt>Protocol</dt><dd class="missing" id="protocol-state">NOT SUPPLIED</dd></div><div><dt>Network job</dt><dd id="durable-job">—</dd></div></dl></section>
      <section class="panel queue"><div class="head"><b>FEASIBILITY × PORTFOLIO PRIORITY</b><span id="queue-meta">—</span></div><div class="queue-head"><span>EDGE</span><span>MAP</span><span>HEAVY</span><span>FEAS.</span><span>PRIORITY</span></div><div id="edge-queue" class="queue-list"></div></section>
        <section class="panel boundary"><div class="head"><b>DECISION BOUNDARY</b><span>ENFORCED</span></div><div class="decision-lines"><span><b>ENGINEERING NEXT</b>FLU→CL end-to-end positive control</span><span><b>PROJECT NEXT</b>UNDECIDABLE · benchmark is not project SAR</span><span id="topology-state"><b>SCORE-FILTERED GRAPH</b>CHECKING TOPOLOGY</span></div><div><b>0</b><span>edge results · execution locked</span></div></section>
    </aside>
    <section class="center-col">
      <section class="panel network"><div class="head"><b>RBFE MAPPING NETWORK · NOT AN FEP RESULT</b><span id="network-meta">OPENFE · LOMAP + KARTOGRAF</span></div><div class="legend"><span class="ready">SCORE ≥ 0.80</span><span class="review">0.50–0.79</span><span class="blocked">&lt; 0.50</span><span class="selected">SELECTED</span></div><div id="network-graph" class="network-graph"><svg id="edge-layer"></svg><div id="node-layer"></div></div></section>
      <section class="center-bottom">
        <section class="panel transform"><div class="head"><b>SELECTED ATOM-MAPPING PROPOSAL</b><span id="transform-name">—</span></div><div class="transform-pair"><div><small>PARENT · CYAN MAPPED / RED SERVER-ATTESTED UNMAPPED</small><b id="left-name">—</b><div id="left-structure" class="structure"></div></div><i>→</i><div><small>PROPOSAL · CYAN MAPPED / GREEN SERVER-ATTESTED UNMAPPED</small><b id="right-name">—</b><div id="right-structure" class="structure"></div></div></div><div id="change-ledger" class="change-ledger"></div><div class="mapping-strip"><span>HEAVY MAP <b id="mapped-atoms">—</b></span><span>LOMAP SCORE <b id="mapping-score">—</b></span><span>INDEX-EXACT Δ <b id="mapping-disagreement">—</b></span><span>CHANGE GATE <b id="chemical-change">—</b></span></div></section>
        <section class="panel atlas"><div class="head"><b>MAPPING EVIDENCE ATLAS</b><span id="atlas-meta">ALL EDGES</span></div><canvas id="risk-canvas" role="img" aria-label="Visual mapping evidence atlas. Use the keyboard-accessible edge queue to select an edge."></canvas><div id="atlas-tooltip" class="atlas-tooltip">HOVER / CLICK POINT</div><div class="axis x">MIN HEAVY COVERAGE →</div><div class="axis y">INDEX-EXACT MAPPER Δ ↓</div></section>
      </section>
    </section>
    <aside class="right-col">
      <section class="panel inspector"><div class="head"><b>EDGE INSPECTOR</b><span id="edge-gate">—</span></div><div class="edge-title"><b id="edge-title">—</b><span id="edge-id">—</span></div><div class="inspector-grid"><div><small>LOMAP SCORE · 0–1 ↑</small><b id="inspect-score">—</b></div><div><small>OPENFE MAP · ALL / HEAVY</small><b id="inspect-atoms">—</b></div><div><small>MORGAN TANIMOTO · 0–1 ↑</small><b id="inspect-tanimoto">—</b></div><div><small>HEAVY MAPPER Δ · 0–1 ↓</small><b id="inspect-jaccard">—</b></div></div><div class="coverage"><span>LEFT HEAVY-ATOM COVERAGE<i id="left-coverage"></i></span><span>RIGHT HEAVY-ATOM COVERAGE<i id="right-coverage"></i></span></div></section>
      <section class="panel execution"><div class="head"><b>PREPARE FEP SYSTEM</b><span>GUI → OPENFE</span></div><div class="system-picker"><label><span>1 · PREPARED RECEPTOR / POSE SET</span><select id="system-select" aria-label="Prepared receptor and aligned pose set"><option value="">READING PREPARED SYSTEMS…</option></select></label><b id="system-status">NO SYSTEM SELECTED</b></div><div class="source-files"><div class="source-tile bound-source"><small>2 · RECEPTOR</small><b id="receptor-state">SERVER ARTIFACT</b><span>CONTENT-ATTESTED</span></div><div class="source-tile bound-source"><small>3 · PARENT POSE</small><b id="parent-pose-state">AUTO-MATCH EDGE</b><span>RECEPTOR-ALIGNED</span></div><div class="source-tile bound-source"><small>4 · PROPOSAL POSE</small><b id="proposal-pose-state">AUTO-MATCH EDGE</b><span>RECEPTOR-ALIGNED</span></div></div><div class="protocol-card"><div><small>5 · PROTOCOL</small><b>OPENFE RFE STANDARD</b><span>REPEX · 11 λ · 1 ns EQ + 5 ns PROD</span></div><span>AMBER ff14SB<br>OpenFF 2.2.1<br>TIP3P · 0.15 M</span></div><div class="not-run"><b id="contract-gate">SELECT A PREPARED SYSTEM</b><span id="contract-detail">The browser sends references only. Dirac resolves receptor and aligned poses, verifies their digests and coordinate frame, then builds both legs.</span></div><section id="operation-confirmation" class="operation-confirmation" aria-live="polite"><b>EXACT OPERATION CONFIRMATION · INCOMPLETE</b><span>START remains locked until plan, system, endpoint poses and edge artifacts are all visible here.</span></section><div class="execution-actions"><button id="validate-contract" disabled>BUILD + VALIDATE 2 LEGS</button><button id="prepare-edge" disabled>START 6 JOBS</button></div></section>
      <section class="panel diagnostics"><div class="head"><b>OPENFE EXECUTION</b><span id="execution-meta">NO RUN DATA</span></div><div class="diag-tabs"><button class="active">JOBS</button><button disabled id="overlap-tab">OVERLAP</button><button disabled id="convergence-tab">CONVERGENCE</button><button disabled>λ WINDOWS</button><button id="cancel-run" disabled>CANCEL</button><button id="retry-run" disabled>RETRY FAILED</button></div><div class="job-matrix" id="job-matrix"><div class="job-empty"><b>AWAITING SERVER PREFLIGHT</b><span>Six physical jobs will appear here: complex/solvent × repeats 1–3.</span></div></div></section>
      <section class="panel aggregate"><div class="head"><b>SELECTED-EDGE AGGREGATION</b><span>RBFE RESULT</span></div><div class="aggregate-state"><b id="aggregate-state">NOT COMPUTED</b><span id="aggregate-detail">Needs paired complex/solvent observations and three governed repeat executions.</span></div><div class="aggregate-grid"><div><small>PASSED LEGS</small><b id="accepted-legs">0 / 6</b></div><div><small>CONVERGENCE</small><b id="aggregate-convergence">—</b></div><div><small>RELATIVE ΔΔG</small><b id="aggregate-ddg">—</b></div></div><button id="aggregate-results" disabled>SERVER AGGREGATES AUTOMATICALLY</button></section>
    </aside>
  </main>
  <footer><span><b id="footer-job">JOB —</b> · immutable rbfe.network artifact</span><span>NETWORK PLAN ≠ FREE ENERGY RESULT</span><span id="footer-artifact">ARTIFACT —</span></footer>
  <dialog id="campaign-builder" class="campaign-builder" aria-labelledby="campaign-builder-title" aria-describedby="campaign-builder-boundary">
    <header class="builder-topbar fep-topbar">
      <div class="builder-title"><button id="close-builder" aria-label="Close new FEP builder">←</button><span><small>NEW CAMPAIGN</small><b id="campaign-builder-title">BUILD A NEW FEP</b></span></div>
      <nav class="workspace-mode-tabs" aria-label="FEP workspace mode"><button id="builder-build" class="active" aria-pressed="true">BUILD</button><button id="builder-review" aria-pressed="false">REVIEW NETWORK</button><button id="builder-runs" aria-pressed="false">RUNS</button></nav>
      <div class="prototype-boundary" id="campaign-builder-boundary"><i></i><span><b>NETWORK PLANNER CONNECTED</b><small>PHYSICAL RUNS REMAIN GATED</small></span></div>
    </header>
    <div class="builder-body">
      <main class="builder-inputs">
        <div class="zone-heading"><span><small>YOU CONTROL THESE</small><b>INPUTS &amp; SCIENTIFIC DECISIONS</b></span><em>EDITABLE</em></div>
        <div class="builder-grid">
          <section class="build-card target-card">
            <div class="build-card-head"><span><small>01</small><b>TARGET &amp; RECEPTOR</b></span><em>REQUIRED</em></div>
            <div class="source-tabs" role="group" aria-label="Receptor source"><button id="source-tab-pdb" class="active" aria-pressed="true" data-target-source="pdb">PDB ID</button><button id="source-tab-upload" aria-pressed="false" data-target-source="upload">UPLOAD STRUCTURE</button><button id="source-tab-existing" aria-pressed="false" data-target-source="existing">DATABASE</button></div>
            <div id="source-pdb-panel" class="source-panel"><label class="hero-input"><span>STRUCTURE ACCESSION</span><div><input id="campaign-pdb" value="" placeholder="ENTER A NEW PDB ID" autocomplete="off" spellcheck="false"><button id="inspect-pdb">FETCH &amp; INSPECT</button></div></label></div>
            <div id="source-upload-panel" class="source-panel" hidden><label class="source-drop"><input id="receptor-file" type="file" accept=".pdb,.ent"><i>＋</i><span><b>DROP RAW PDB</b><small>Dirac prepares the protein after upload; do not pre-build an OpenFE system.</small></span><em>SELECT FILE</em></label></div>
            <div id="source-existing-panel" class="source-panel" hidden><label class="hero-input"><span>VERSIONED RECEPTOR ASSET</span><div><select id="builder-system-select"><option value="">NO REGISTERED SYSTEM SELECTED</option></select><button id="inspect-existing">INSPECT PROVENANCE</button></div></label></div>
            <div class="receptor-preview">
              <div class="pocket-glyph" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><span></span></div>
              <div><small>START FROM RAW EXPERIMENTAL STRUCTURE</small><b id="receptor-preview-title">NO RECEPTOR SELECTED</b><span id="receptor-preview-detail">Enter a PDB ID or upload fixed-column PDB coordinates.</span></div>
            </div>
            <div class="decision-row"><label><span>COORDINATES</span><select id="assembly-select" data-invalidate="receptor"><option value="deposited_asymmetric_unit">Deposited asymmetric unit</option></select></label><label><span>ANCHOR ROLE FILTER</span><select id="site-role-filter" data-invalidate="reference"><option value="ligand">DRUG-LIKE LIGANDS</option><option value="all">ALL ORGANIC HET GROUPS</option></select></label><label><span>BOUND REFERENCE LIGAND</span><select id="site-select" data-invalidate="reference" disabled><option value="">FETCH A STRUCTURE FIRST</option></select></label></div>
            <button class="advanced-trigger" data-advanced="receptor">PROTEIN PREPARATION OPTIONS <span>＋</span></button>
            <div class="inline-policy"><label><span>MISSING ATOMS</span><select id="prep-missing-atoms" data-invalidate="prep"><option value="auto_repair_report">AUTO-REPAIR + REPORT</option><option value="review_each">REVIEW EACH</option><option value="block">BLOCK IF MISSING</option></select></label><label><span>MISSING RESIDUES</span><select id="prep-missing-residues" data-invalidate="prep"><option value="block">BLOCK IF MISSING</option><option value="review_each">REVIEW EACH</option><option value="auto_repair_report">AUTO-REPAIR + REPORT</option></select></label><label><span>ALTLOCS</span><select id="prep-altloc" data-invalidate="prep"><option value="review_each">REVIEW EACH</option><option value="highest_occupancy">HIGHEST OCCUPANCY + REPORT</option><option value="block_ambiguous">BLOCK AMBIGUOUS</option></select></label><label><span>ZERO OCCUPANCY</span><select id="prep-occupancy" data-invalidate="prep"><option value="review_zero">REVIEW ZERO-OCC ATOMS</option><option value="reject_zero">REJECT ZERO-OCC ATOMS</option><option value="keep_reported">KEEP + REPORT</option></select></label><label><span>PROTONATION</span><select id="prep-protonation" data-invalidate="prep"><option value="server_assign_review">pH 7.4 · SERVER ASSIGN + REVIEW</option><option value="manual">MANUAL REVIEW</option></select></label><label><span>POCKET WATERS</span><select id="prep-waters" data-invalidate="prep" title="Per-water review is locked until identity, occupancy, B-factor, distance and reason decisions are implemented"><option value="remove_all">REMOVE ALL · SAFE DEFAULT</option><option value="review_pocket" disabled>REVIEW ≤ 5 Å · LOCKED: NEED PER-WATER DECISIONS</option><option value="keep_all">KEEP ALL · SERVER POLICY GATE</option></select></label><label><span>COFACTORS</span><select id="prep-cofactors" data-invalidate="prep"><option value="keep_parameter_gate">KEEP + PARAMETER GATE</option><option value="review_each">REVIEW EACH</option><option value="remove">REMOVE</option></select></label><label><span>METALS</span><select id="prep-metals" data-invalidate="prep"><option value="keep_parameter_gate">KEEP + PARAMETER GATE</option><option value="review_each">REVIEW EACH</option><option value="remove">REMOVE</option></select></label></div>
          </section>
          <section class="build-card ligand-card">
            <div class="build-card-head"><span><small>02</small><b>LIGAND SERIES</b></span><em id="ligand-count-label">0 VALID</em></div>
            <div class="ligand-actions"><button id="paste-smiles" class="active">PASTE SMILES</button><button id="draw-ligand">DRAW</button><label class="file-button" for="ligand-file">UPLOAD SDF / MOL<input id="ligand-file" type="file" accept=".sdf,.sd,.mol" data-invalidate="ligands"></label></div>
            <label class="series-editor"><span><b>ID</b><b>SMILES</b><b>STATE</b></span><textarea id="campaign-ligands" placeholder="Draw molecules or paste one ID + SMILES per line" spellcheck="false"></textarea></label>
            <div class="ligand-summary"><span><b id="ligand-valid-count">0</b><small>POLICY-READY MOLECULES</small></span><span><b id="ligand-charge-count">0</b><small>NONZERO FORMAL CHARGE</small></span><span><b id="ligand-heavy-median">—</b><small>HEAVY ATOMS · MEDIAN</small></span><button id="validate-ligands">VALIDATE SERIES</button></div>
            <section class="ligand-identity-audit" aria-labelledby="ligand-identity-title"><div><b id="ligand-identity-title">MOLECULAR IDENTITY AUDIT</b><span>EVERY NON-EMPTY ROW GETS A VERDICT</span></div><div id="ligand-identity-rows"><p>NO LIGAND ROWS · NOTHING VALIDATED</p></div></section>
            <button class="advanced-trigger" data-advanced="ligands">MICROSTATES &amp; CHARGE POLICY <span>＋</span></button>
            <div class="inline-policy ligand-policy"><label><span>PROTONATION</span><select id="ligand-ph" data-invalidate="ligands"><option value="enumerate_at_ph">ENUMERATE AT pH 7.4 ± 0.5</option><option value="specified_only">SPECIFIED STATES ONLY</option></select></label><label><span>TAUTOMERS</span><select id="ligand-tautomers" data-invalidate="ligands"><option value="enumerate">ENUMERATE + REPORT</option><option value="dominant_only">DOMINANT ONLY</option><option value="strict">STRICT INPUT IDENTITY</option></select></label><label><span>STEREO</span><select id="ligand-stereo" data-invalidate="ligands"><option value="preserve_block_unknown">PRESERVE SPECIFIED · BLOCK UNKNOWN</option><option value="enumerate_unknown">ENUMERATE UNKNOWN</option></select></label><label><span>STATE POPULATION</span><select id="ligand-state-cutoff" data-invalidate="ligands"><option value="0.1">≥ 10%</option><option value="0.05">≥ 5%</option></select></label><label><span>CHARGE EDGES</span><select id="ligand-charge-policy" data-invalidate="ligands"><option value="block_changes">BLOCK BY DEFAULT</option><option value="allow_governed">ALLOW GOVERNED</option></select></label></div>
          </section>
          <section class="build-card pose-card">
            <div class="build-card-head"><span><small>03</small><b>POSE GENERATION</b></span><em>CHOOSE METHOD</em></div>
            <div class="strategy-cards" data-choice-group="pose">
              <button id="pose-choice-align" class="choice-card active" data-choice="align" data-invalidate="pose"><i class="choice-icon align"></i><span><b>ALIGN TO REFERENCE</b><small>Keep the crystallographic core fixed; generate analog coordinates from atom mapping.</small></span><em>RECOMMENDED</em></button>
              <button id="pose-choice-dock" class="choice-card" data-choice="dock" disabled title="Docking pose review is a separate workflow and is not connected in this release"><i class="choice-icon dock"></i><span><b>DOCK TO POCKET</b><small>Separate workflow: ensemble generation, clustering and pose review.</small></span><em>NOT CONNECTED</em></button>
              <button id="pose-choice-upload" class="choice-card" data-choice="upload" disabled title="Imported-pose review is a separate workflow and is not connected in this release"><i class="choice-icon upload"></i><span><b>USE EXISTING POSES</b><small>Separate workflow: verify SDF coordinates against this receptor frame.</small></span><em>NOT CONNECTED</em></button>
            </div>
            <div class="pose-contract"><span><small>REFERENCE LIGAND</small><b id="pose-reference-state">SELECT AFTER RECEPTOR INSPECTION</b></span><span><small>CORE POLICY</small><b>CRYSTAL CORE · MCS ≥ 50%</b></span><span><small>POSE REVIEW</small><b id="pose-review-state">REQUIRED BEFORE RUN</b></span></div>
            <div class="acceptance-gates"><b>POSE ACCEPTANCE GATES</b><span><i>CORE RMSD</i><em>≤ 1.0 Å</em></span><span><i>PROTEIN CLASH</i><em>0 ALLOWED</em></span><span><i>POCKET CONTACT</i><em>≥ 1 REQUIRED</em></span><span><i>HUMAN REVIEW</i><em class="pending">PENDING</em></span></div>
          </section>
          <section class="build-card plan-card">
            <div class="build-card-head"><span><small>04</small><b>NETWORK &amp; PROTOCOL</b></span><em>ESTIMATE BEFORE RUN</em></div>
            <div class="plan-columns"><div><small>NETWORK STRATEGY</small><div class="mini-options" data-choice-group="network"><button id="network-choice-balanced" class="active" data-choice="balanced" data-invalidate="network"><b>BALANCED</b><span>Connected graph + redundancy</span></button><button id="network-choice-minimum" data-choice="minimum" data-invalidate="network"><b>MINIMUM</b><span>Lowest compute, least closure</span></button><button id="network-choice-dense" data-choice="dense" data-invalidate="network"><b>DENSE</b><span>More cycles, higher cost</span></button></div></div><div><small>SIMULATION PROTOCOL</small><div class="protocol-choice"><select id="protocol-select" data-invalidate="protocol"><option value="openfe-rfe-standard-v1">Standard · 11 λ · 5 ns</option></select><dl><div><dt>Protein</dt><dd>AMBER ff14SB</dd></div><div><dt>Ligand</dt><dd>OpenFF 2.2.1</dd></div><div><dt>Water</dt><dd>TIP3P · 0.15 M</dd></div><div><dt>Repeats</dt><dd>3 / leg</dd></div></dl></div></div></div>
            <div class="run-estimate"><span><small>PLANNED EDGES</small><b>3</b></span><span><small>LEGS / EDGE</small><b>2</b></span><span><small>REPEATS / LEG</small><b>3</b></span><span><small>PHYSICAL JOBS</small><b>18</b></span><span><small>GPU ESTIMATE</small><b>~90 h</b></span></div>
          </section>
        </div>
      </main>
      <aside class="builder-output">
        <div class="zone-heading generated"><span><small>DIRAC CREATES THESE</small><b>GENERATED ARTIFACTS &amp; GATES</b></span><em>READ-ONLY</em></div>
        <section class="output-preview">
          <div class="output-preview-head"><span><small>CAMPAIGN</small><input id="campaign-name" value="UNTITLED FEP CAMPAIGN" aria-label="Campaign name"></span><b>EMPTY</b></div>
          <div class="generated-system">
            <div class="system-orbit"><span class="protein-mark"></span><i class="ligand-mark one"></i><i class="ligand-mark two"></i><i class="ligand-mark three"></i></div>
            <div><small>PROPOSED SYSTEM</small><b id="proposed-system-title">NO RECEPTOR · 0 LIGANDS · NOT PLANNED</b><span>Coordinates must share one receptor frame. Dirac versions every generated artifact and records its digest.</span></div>
          </div>
          <section class="preparation-policy-audit" aria-labelledby="preparation-policy-title"><div><b id="preparation-policy-title">PREPARATION POLICY EXECUTION</b><span id="preparation-policy-summary">NOT GENERATED</span></div><div id="preparation-policy-rows"><p>Backend evidence appears here after receptor and pose preparation.</p></div></section>
          <ol class="artifact-pipeline">
            <li data-pipeline="receptor"><span>1</span><div><b>PREPARED RECEPTOR STATE</b><small>Repair · protonate · retain reviewed waters · freeze coordinate frame</small></div><em>WILL BUILD</em></li>
            <li data-pipeline="states"><span>2</span><div><b>LIGAND STATE ENSEMBLE</b><small>Canonical identities · protonation · tautomer · stereo · formal charge</small></div><em>WILL BUILD</em></li>
            <li data-pipeline="poses"><span>3</span><div><b>RECEPTOR-ALIGNED POSES</b><small>Reference-constrained coordinates · clash/contact checks · pose provenance</small></div><em>WILL BUILD</em></li>
            <li data-pipeline="network"><span>4</span><div><b>RBFE NETWORK &amp; ATOM MAPS</b><small>OpenFE planner · LoMap + Kartograf comparison · topology gates</small></div><em>WILL PLAN</em></li>
            <li data-pipeline="transforms"><span>5</span><div><b>COMPLEX + SOLVENT TRANSFORMATIONS</b><small>GUFE objects generated server-side; never uploaded or edited as JSON</small></div><em>WILL FREEZE</em></li>
          </ol>
          <div class="network-miniature empty" aria-label="Network preview awaiting new molecules"><svg viewBox="0 0 400 120"></svg><div class="empty-network" id="network-preview-message">DRAW AT LEAST TWO MOLECULES<br><small>NETWORK WILL BE GENERATED FROM YOUR NEW SERIES</small></div><div><span><b id="preview-node-count">0</b> NODES</span><span><b id="preview-edge-count">0</b> EDGES</span><span><b id="preview-job-count">0</b> PHYSICAL JOBS</span><span><b id="preview-hours">—</b> GPU HOURS</span></div></div>
        </section>
        <section class="portfolio-card" aria-labelledby="portfolio-title"><div class="readiness-head"><b id="portfolio-title">PORTFOLIO DECISION CONTRACT</b><span>PRIORITY ≠ FEASIBILITY</span></div><div class="portfolio-grid"><label><span>PROJECT QUESTION</span><input id="campaign-question" data-invalidate="portfolio" placeholder="Which decision will this edge change?"></label><label><span>ASSAY / POTENCY ANCHOR</span><input id="assay-anchor" data-invalidate="portfolio" placeholder="Assay, endpoint, value, units"></label><label><span>SELECTIVITY</span><input id="selectivity-context" data-invalidate="portfolio" placeholder="Panel and required margin"></label><label><span>ADME / DDI</span><input id="adme-context" data-invalidate="portfolio" placeholder="Clearance, exposure, liabilities"></label><label><span>SYNTHESIS STATUS</span><select id="synthesis-status" data-invalidate="portfolio"><option value="">UNSPECIFIED</option><option>IN HAND</option><option>ROUTE READY</option><option>ROUTE RISK</option><option>IDEA ONLY</option></select></label><label><span>PORTFOLIO PRIORITY</span><select id="portfolio-priority" data-invalidate="portfolio"><option value="">UNRANKED</option><option>HIGH · DECISION-CHANGING</option><option>MEDIUM · SUPPORTING</option><option>LOW · EASY BUT NON-DECISIVE</option></select></label><label class="portfolio-wide"><span>COMPOUND PRIORITIES · ONE PER LINE</span><textarea id="compound-priorities" data-invalidate="portfolio" placeholder="COMPOUND_ID | HIGH/MEDIUM/LOW | decision rationale | synthesis status"></textarea></label><label><span>UNCERTAINTY / POSE HYPOTHESIS</span><input id="pose-hypothesis" data-invalidate="portfolio" placeholder="Expected pose and largest uncertainty"></label><label><span>COST CAP</span><input id="cost-cap" data-invalidate="portfolio" placeholder="GPU hours or budget ceiling"></label><label><span>NEXT ACTION</span><input id="next-action" data-invalidate="portfolio" placeholder="Action if result is positive/negative"></label><label><span>STOP RULE</span><input id="stop-rule" data-invalidate="portfolio" placeholder="Outcome that kills or defers this edge"></label></div></section>
        <section class="readiness-contract"><div class="readiness-head"><b>CREATION CONTRACT</b><span id="draft-readiness">EMPTY · INPUTS REQUIRED</span></div><div class="gate-row pending" id="structure-gate"><i>○</i><span><b>STRUCTURE + REFERENCE</b><small>No receptor selected</small></span></div><div class="gate-row pending" id="ligand-gate"><i>○</i><span><b>PARENT + ANALOGUES</b><small>No new molecules yet</small></span></div><div class="gate-row pending" id="portfolio-gate"><i>○</i><span><b>DECISION CONTEXT</b><small>Question, assay anchor, next action and stop rule required</small></span></div><div class="gate-row pending" id="generated-gate"><i>○</i><span><b>GENERATED SCIENCE</b><small>Not computed until campaign preparation starts</small></span></div><p>“READY” means only that the next operation is legal. Interactive inputs are not evidence; generated artifacts remain read-only.</p></section>
      </aside>
    </div>
    <footer class="builder-actionbar"><div><button id="save-draft">SAVE DRAFT</button><button id="resume-draft">RESUME DRAFT</button><label class="file-button compact" for="import-campaign-file">IMPORT CAMPAIGN<input id="import-campaign-file" type="file" accept="application/json,.json"></label><button id="clear-campaign">CLEAR CAMPAIGN</button><button id="archive-planner-receipt" hidden>ARCHIVE PLANNER RECEIPT</button><button id="cancel-preparation" hidden>REQUEST PREP CANCEL</button><button id="detach-preparation" hidden>DETACH PREP WAIT</button></div><span><b id="builder-next-label">NEXT · ADD RECEPTOR + NEW MOLECULES</b><small>No prepared receptor or OpenFE JSON is required from the user.</small></span><button id="review-inputs" class="review-inputs" disabled>REVIEW INPUTS →</button></footer>
    <div id="builder-notice" class="builder-notice" role="status" aria-live="assertive"></div>
  </dialog>
  <dialog id="molecule-sketcher" class="molecule-sketcher" aria-labelledby="sketcher-title" aria-hidden="true"></dialog>
  <dialog id="pose-reviewer" class="pose-reviewer" aria-labelledby="pose-review-title" aria-hidden="true"></dialog>
  </div>`
}
