#!/usr/bin/env python3
"""Validate canonical domain/command contracts and generate Python + TypeScript."""
from __future__ import annotations

import json
import pathlib
import copy
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOMAIN = ROOT / 'contracts/domain/object-kinds.json'
RELATIONS = ROOT / 'contracts/domain/relations.json'
COMMANDS = ROOT / 'contracts/commands/registry.json'
OUT_PY = ROOT / 'contracts/generated/python/commands.py'
OUT_TS = ROOT / 'contracts/generated/typescript/commands.ts'
SDK_PY = ROOT / 'python/src/dirac/generated_contracts.py'
APP_TS = ROOT / 'src/app/generated/commands.ts'


def validate(domain: dict, relations: dict, registry: dict) -> None:
    kinds = domain.get('kinds') or []
    if len(kinds) != len(set(kinds)) or len(kinds) < 20:
        raise ValueError('ObjectKind registry is duplicate or suspiciously incomplete')
    rels = relations.get('relations') or []
    if len(rels) != len(set(rels)):
        raise ValueError('relation registry contains duplicates')
    required = {'id', 'version', 'input_schema', 'output_schema', 'category',
                'mutability', 'execution_class', 'executors', 'idempotency_policy',
                'job_policy', 'provenance_policy', 'input_object_kinds',
                'output_object_kinds', 'errors', 'handler'}
    ids: set[str] = set()
    error_ids = set(json.loads((ROOT / 'contracts/errors.json').read_text())['codes'])
    for command in registry.get('commands') or []:
        cid = command.get('id', '<missing>')
        missing = required - set(command)
        if missing:
            raise ValueError(f'{cid}: missing {sorted(missing)}')
        if cid in ids:
            raise ValueError(f'duplicate command id {cid}')
        ids.add(cid)
        unknown = (set(command['input_object_kinds'])
                   | set(command['output_object_kinds'])) - set(kinds)
        if unknown:
            raise ValueError(f'{cid}: unknown ObjectKinds {sorted(unknown)}')
        unknown_errors = set(command['errors']) - error_ids
        if unknown_errors:
            raise ValueError(f'{cid}: unknown errors {sorted(unknown_errors)}')
        if command['job_policy'] == 'required' and command['execution_class'] != 'long':
            raise ValueError(f'{cid}: required job must have execution_class=long')
    if len(ids) < 10:
        raise ValueError('command registry is suspiciously incomplete')


def load_and_validate() -> tuple[dict, dict, dict]:
    domain = json.loads(DOMAIN.read_text())
    relations = json.loads(RELATIONS.read_text())
    registry = json.loads(COMMANDS.read_text())
    validate(domain, relations, registry)
    return domain, relations, registry


def selftest(domain: dict, relations: dict, registry: dict) -> None:
    """Prove the validator rejects drift instead of merely passing good input."""
    bad = copy.deepcopy(registry)
    bad['commands'].append(copy.deepcopy(bad['commands'][0]))
    try:
        validate(domain, relations, bad)
    except ValueError as error:
        if 'duplicate command id' not in str(error):
            raise AssertionError(f'wrong duplicate conviction: {error}') from error
    else:
        raise AssertionError('validator accepted a duplicate command id')

    bad = copy.deepcopy(registry)
    bad['commands'][0]['output_object_kinds'] = ['not_a_real_kind']
    try:
        validate(domain, relations, bad)
    except ValueError as error:
        if 'unknown ObjectKinds' not in str(error):
            raise AssertionError(f'wrong ObjectKind conviction: {error}') from error
    else:
        raise AssertionError('validator accepted an unknown ObjectKind')


def render_py(domain: dict, relations: dict, registry: dict) -> str:
    kinds = domain['kinds']; rels = relations['relations']
    ids = [c['id'] for c in registry['commands']]
    return f'''"""GENERATED by scripts/gen_commands.py. Do not edit."""
from __future__ import annotations
from typing import Literal, TypedDict

ObjectKind = Literal[{', '.join(repr(x) for x in kinds)}]
RelationKind = Literal[{', '.join(repr(x) for x in rels)}]
CommandId = Literal[{', '.join(repr(x) for x in ids)}]

class ObjectRef(TypedDict):
    kind: ObjectKind
    id: str

OBJECT_KINDS = {kinds!r}
RELATION_KINDS = {rels!r}
COMMAND_IDS = {ids!r}
'''


def render_ts(domain: dict, relations: dict, registry: dict) -> str:
    union = lambda xs: ' | '.join(repr(x) for x in xs)
    items = [{k: c[k] for k in ('id', 'version', 'category', 'mutability',
                                 'execution_class', 'executors', 'job_policy',
                                 'provenance_policy', 'input_object_kinds',
                                 'output_object_kinds')}
             for c in registry['commands']]
    return f'''/** GENERATED by scripts/gen_commands.py. Do not edit. */
export type ObjectKind = {union(domain['kinds'])};
export type RelationKind = {union(relations['relations'])};
export type CommandId = {union([c['id'] for c in registry['commands']])};

export type ObjectRef<K extends ObjectKind = ObjectKind> = {{ kind: K; id: string }};
export type ActorRef = {{ kind: 'human' | 'agent' | 'service'; id: string }};

export const OBJECT_KINDS = {json.dumps(domain['kinds'], indent=4)} as const;
export const RELATION_KINDS = {json.dumps(relations['relations'], indent=4)} as const;
export const COMMANDS = {json.dumps(items, indent=4)} as const;
'''


def main() -> int:
    check = '--check' in sys.argv
    try:
        domain, relations, registry = load_and_validate()
    except Exception as error:                                      # noqa: BLE001
        print(f'gen_commands: {error}', file=sys.stderr)
        return 1
    if '--selftest' in sys.argv:
        selftest(domain, relations, registry)
    py_text = render_py(domain, relations, registry)
    ts_text = render_ts(domain, relations, registry)
    expected = {OUT_PY: py_text, SDK_PY: py_text,
                OUT_TS: ts_text, APP_TS: ts_text}
    stale = []
    for path, text in expected.items():
        if not path.exists() or path.read_text() != text:
            stale.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text)
    if check and stale:
        print('gen_commands: stale generated files: '
              + ', '.join(str(p.relative_to(ROOT)) for p in stale), file=sys.stderr)
        return 1
    print(f'command contracts OK · {len(domain["kinds"])} ObjectKinds · '
          f'{len(registry["commands"])} commands · '
          + ('up to date' if not stale else 'generated')
          + (' · redproof passed' if '--selftest' in sys.argv else ''))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
