#!/usr/bin/env python3
"""Generate Python and TypeScript from the canonical contracts, or fail if stale.

ADR-002: `contracts/schema/*.schema.json` and `contracts/methods/*.method.json` are
the ROOT source. Everything typed is generated from them. This script is that
generator and, with `--check`, the gate that makes editing a schema without
regenerating a red build.

WHY GENERATED AND NOT HAND-WRITTEN, measured rather than argued: `contracts/iface.pyi`
still marks `register_method` and `job_create` as `PLANNED seam` while both landed
hours ago (3 occurrences). Three times in one day an undeclared response key was
live in production. Hand-synchronised declarations describe the system their author
last remembered.

WHAT IT VALIDATES, and the second one is the one a wrapper-only checker misses:
  1. every descriptor against contracts/schema/method-descriptor.schema.json
  2. every descriptor's OWN input/output schema, as a schema — a descriptor can be
     structurally perfect while carrying a `type: "objekt"` inside it, and the only
     thing that catches that is validating the nested schema itself
  3. every declared example against the input schema it claims to satisfy

Usage:  python3 scripts/gen_contracts.py [--check]
Exit:   0 written / up to date · 1 stale or invalid · 2 could not run
"""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SCHEMA_DIR = ROOT / 'contracts' / 'schema'
METHOD_DIR = ROOT / 'contracts' / 'methods'
OUT_PY = ROOT / 'contracts' / 'generated' / 'python' / 'methods.py'
OUT_TS = ROOT / 'contracts' / 'generated' / 'typescript' / 'methods.ts'

BANNER = ('GENERATED by scripts/gen_contracts.py from contracts/methods/*.method.json. '
          'Do not edit: run the generator. Gate 7 fails if this file is stale.')


def load_descriptors() -> list[dict]:
    out = []
    for p in sorted(METHOD_DIR.glob('*.method.json')):
        out.append(json.loads(p.read_text(encoding='utf-8')))
    return out


def validate(descriptors: list[dict]) -> list[str]:
    problems: list[str] = []
    try:
        from jsonschema import Draft202012Validator
    except ImportError:
        return ['jsonschema is not importable; validation SKIPPED — which is not the '
                'same as valid, so this is reported as a problem rather than passed']
    meta = json.loads((SCHEMA_DIR / 'method-descriptor.schema.json').read_text())
    Draft202012Validator.check_schema(meta)
    v = Draft202012Validator(meta)
    for d in descriptors:
        mid = d.get('method_id', '<no method_id>')
        for e in v.iter_errors(d):
            problems.append(f'{mid}: {"/".join(str(x) for x in e.path)}: {e.message}')
        for side in ('input', 'output'):
            sch = (d.get(side) or {}).get('schema')
            if sch is None:
                continue
            try:
                Draft202012Validator.check_schema(sch)
            except Exception as exc:                                 # noqa: BLE001
                problems.append(f'{mid}: {side}.schema is not a valid schema: {exc}')
        # ── the descriptor's implementation claim vs the RUNTIME registry ────
        # A descriptor that names functions the registry does not hash is a
        # descriptor whose implementation digest means something else. Compared as
        # SETS: my first version of this check compared LISTS and reported a
        # mismatch on fields.qm.homo that was only ordering — the third time today
        # an instrument, not the data, was wrong. Order is not semantic here.
        impl = d.get('implementation') or {}
        if impl.get('module') == 'backend.field_server':
            try:
                import sys as _sys
                _sys.path.insert(0, str(ROOT / 'backend'))
                import method_registry as _mr                        # noqa: PLC0415
                unit = _mr.UNITS.get(mid)
            except Exception as exc:                                 # noqa: BLE001
                problems.append(f'{mid}: cannot read the runtime registry to '
                                f'cross-check implementation ({exc}) — reported '
                                f'rather than skipped')
                unit = None
            if unit is not None:
                if set(impl.get('functions', ())) != set(unit['fns']):
                    problems.append(
                        f'{mid}: implementation.functions '
                        f'{sorted(set(impl.get("functions", ())))} != registry '
                        f'{sorted(set(unit["fns"]))}')
                if set(impl.get('constants', ())) != set(unit.get('consts', ())):
                    problems.append(
                        f'{mid}: implementation.constants '
                        f'{sorted(set(impl.get("constants", ())))} != registry '
                        f'{sorted(set(unit.get("consts", ())))}')

        in_schema = (d.get('input') or {}).get('schema')
        if in_schema:
            try:
                iv = Draft202012Validator(in_schema)
                for i, ex in enumerate((d.get('input') or {}).get('examples') or []):
                    for e in iv.iter_errors(ex):
                        problems.append(
                            f'{mid}: input.examples[{i}]: '
                            f'{"/".join(str(x) for x in e.path)}: {e.message}')
            except Exception as exc:                                 # noqa: BLE001
                problems.append(f'{mid}: cannot validate examples: {exc}')
    return problems


def py_literal(values: list) -> str:
    return 'Literal[' + ', '.join(json.dumps(v) for v in values) + ']'


def enum_of(schema: dict, *path: str) -> list | None:
    node = schema
    for key in path:
        node = (node or {}).get(key) if isinstance(node, dict) else None
        if node is None:
            return None
    return node.get('enum') if isinstance(node, dict) else None


def render_python(descriptors: list[dict]) -> str:
    lines = ['"""' + BANNER + '"""', 'from __future__ import annotations', '',
             'from typing import Literal, TypedDict', '']
    ids = [d['method_id'] for d in descriptors]
    lines.append('MethodId = ' + py_literal(ids))
    lines.append('')
    for d in descriptors:
        mid = d['method_id']
        cls = ''.join(p.capitalize() for p in mid.replace('.', '_').split('_'))
        params = ((d['input']['schema'].get('properties') or {})
                  .get('parameters', {}).get('properties') or {})
        lines.append(f'# {mid} — {d["summary"]}')
        if params:
            lines.append(f'class {cls}Parameters(TypedDict, total=False):')
            for name, spec in params.items():
                if spec.get('enum'):
                    t = py_literal(spec['enum'])
                elif spec.get('type') == 'integer':
                    t = 'int'
                elif isinstance(spec.get('type'), list):
                    t = ' | '.join({'integer': 'int', 'number': 'float',
                                    'string': 'str', 'null': 'None'}.get(x, 'object')
                                   for x in spec['type'])
                else:
                    t = {'number': 'float', 'string': 'str',
                         'boolean': 'bool'}.get(spec.get('type'), 'object')
                lines.append(f'    {name}: {t}')
            lines.append('')
        # repr(), NOT json.dumps: JSON booleans are `true`/`false` and Python's are
        # `True`/`False`, so a json.dumps'd dict is a NameError the moment the
        # generated module is imported. Caught by importing the output rather than
        # reading it — the generated file looked completely reasonable.
        lines.append(f'{cls.upper()}_EXECUTION = {d["execution"]!r}')
        refusals = sorted({r['code'] for r in d.get('refusals', [])})
        lines.append(f'{cls.upper()}_REFUSALS = {refusals!r}')
        warns = sorted({w['code'] for w in d.get('warnings', [])})
        lines.append(f'{cls.upper()}_WARNINGS = {warns!r}')
        lines.append('')
    lines.append(f'METHOD_IDS = {ids!r}')
    lines.append('')
    return '\n'.join(lines)


def render_typescript(descriptors: list[dict]) -> str:
    lines = ['/** ' + BANNER + ' */', '']
    ids = [d['method_id'] for d in descriptors]
    lines.append('export type MethodId =\n'
                 + '\n'.join(f"    | '{i}'" for i in ids) + ';')
    lines.append('')
    for d in descriptors:
        mid = d['method_id']
        name = ''.join(p.capitalize() for p in mid.replace('.', ' ').split())
        params = ((d['input']['schema'].get('properties') or {})
                  .get('parameters', {}).get('properties') or {})
        lines.append(f'/** {mid} — {d["summary"]} */')
        if params:
            lines.append(f'export interface {name}Parameters {{')
            for pname, spec in params.items():
                if spec.get('enum'):
                    t = ' | '.join(f"'{v}'" for v in spec['enum'])
                elif isinstance(spec.get('type'), list):
                    t = ' | '.join({'integer': 'number', 'number': 'number',
                                    'string': 'string', 'null': 'null'}.get(x, 'unknown')
                                   for x in spec['type'])
                else:
                    t = {'integer': 'number', 'number': 'number', 'string': 'string',
                         'boolean': 'boolean'}.get(spec.get('type'), 'unknown')
                lines.append(f'    {pname}?: {t};')
            lines.append('}')
            lines.append('')
        lines.append(f'export const {name}Execution = '
                     + json.dumps(d['execution'], indent=4) + ' as const;')
        lines.append('')
    lines.append('export const METHOD_IDS: readonly MethodId[] = '
                 + json.dumps(ids, indent=4) + ' as const;')
    lines.append('')
    return '\n'.join(lines)


def main() -> int:
    check = '--check' in sys.argv
    descriptors = load_descriptors()
    if not descriptors:
        print('gen_contracts: no descriptors in contracts/methods — refusing to '
              'write empty generated files, which would read as "nothing to do"',
              file=sys.stderr)
        return 2

    problems = validate(descriptors)
    if problems:
        print(f'{len(problems)} contract problem(s):', file=sys.stderr)
        for p in problems[:20]:
            print(f'  {p}', file=sys.stderr)
        return 1

    want = {OUT_PY: render_python(descriptors), OUT_TS: render_typescript(descriptors)}
    stale = []
    for path, text in want.items():
        current = path.read_text(encoding='utf-8') if path.exists() else None
        if current != text:
            stale.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding='utf-8')

    rel = lambda p: p.relative_to(ROOT)                              # noqa: E731
    if check and stale:
        print('GENERATED FILES ARE STALE: ' + ', '.join(str(rel(p)) for p in stale),
              file=sys.stderr)
        print('Run: python3 scripts/gen_contracts.py', file=sys.stderr)
        return 1
    verb = 'up to date' if check else ('wrote ' + ', '.join(str(rel(p)) for p in stale)
                                       if stale else 'already current')
    print(f'{len(descriptors)} descriptor(s) valid · {verb}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
