#!/usr/bin/env python3
"""Generate Python and TypeScript from the canonical contracts, or fail if stale.

ADR-002: `contracts/schema/*.schema.json` and `contracts/methods/*.method.json` are
the ROOT source. Everything typed is generated from them. This script is that
generator and, with `--check`, the gate that makes editing a schema without
regenerating a red build.

WHY GENERATED AND NOT HAND-WRITTEN, measured rather than argued: `contracts/iface.pyi`
still marks `register_method` and `job_create` as `PLANNED seam` while both landed
hours ago (3 occurrences). Three times in one day an undeclared response key was
live in production. Hand-synchronised declarations describe the system their author
last remembered.

WHAT IT VALIDATES, and the second one is the one a wrapper-only checker misses:
  1. every descriptor against contracts/schema/method-descriptor.schema.json
  2. every descriptor's OWN input/output schema, as a schema — a descriptor can be
     structurally perfect while carrying a `type: "objekt"` inside it, and the only
     thing that catches that is validating the nested schema itself
  3. every declared example against the input schema it claims to satisfy

Usage:  python3 scripts/gen_contracts.py [--check]
Exit:   0 written / up to date · 1 stale or invalid · 2 could not run
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SCHEMA_DIR = ROOT / 'contracts' / 'schema'
METHOD_DIR = ROOT / 'contracts' / 'methods'
OUT_PY = ROOT / 'contracts' / 'generated' / 'python' / 'methods.py'
OUT_TS = ROOT / 'contracts' / 'generated' / 'typescript' / 'methods.ts'

BANNER = ('GENERATED by scripts/gen_contracts.py from contracts/methods/*.method.json. '
          'Do not edit: run the generator. Gate 7 fails if this file is stale.')


def load_descriptors() -> list[dict]:
    out = []
    for p in sorted(METHOD_DIR.glob('*.method.json')):
        out.append(json.loads(p.read_text(encoding='utf-8')))
    return out


def validate(descriptors: list[dict]) -> list[str]:
    problems: list[str] = []
    try:
        from jsonschema import Draft202012Validator
    except ImportError:
        return ['jsonschema is not importable; validation SKIPPED — which is not the '
                'same as valid, so this is reported as a problem rather than passed']
    meta = json.loads((SCHEMA_DIR / 'method-descriptor.schema.json').read_text())
    Draft202012Validator.check_schema(meta)
    v = Draft202012Validator(meta)
    for d in descriptors:
        mid = d.get('method_id', '<no method_id>')
        for e in v.iter_errors(d):
            problems.append(f'{mid}: {"/".join(str(x) for x in e.path)}: {e.message}')
        for side in ('input', 'output'):
            sch = (d.get(side) or {}).get('schema')
            if sch is None:
                continue
            try:
                Draft202012Validator.check_schema(sch)
            except Exception as exc:                                 # noqa: BLE001
                problems.append(f'{mid}: {side}.schema is not a valid schema: {exc}')
        # ── the descriptor's implementation claim vs the RUNTIME registry ────
        # A descriptor that names functions the registry does not hash is a
        # descriptor whose implementation digest means something else. Compared as
        # SETS: my first version of this check compared LISTS and reported a
        # mismatch on fields.qm.homo that was only ordering — the third time today
        # an instrument, not the data, was wrong. Order is not semantic here.
        impl = d.get('implementation') or {}
        if impl.get('module'):
            try:
                import sys as _sys
                _sys.path.insert(0, str(ROOT / 'backend'))
                import method_registry as _mr                        # noqa: PLC0415
                unit = _mr.UNITS.get(mid)
            except Exception as exc:                                 # noqa: BLE001
                problems.append(f'{mid}: cannot read the runtime registry to '
                                f'cross-check implementation ({exc}) — reported '
                                f'rather than skipped')
                unit = None
            if unit is None:
                problems.append(
                    f'{mid}: implementation.module is declared but no runtime compute '
                    'unit has that method_id')
            else:
                expected_module = 'backend.' + unit.get('module', 'field_server')
                if impl.get('module') != expected_module:
                    problems.append(
                        f'{mid}: implementation.module {impl.get("module")!r} != '
                        f'registry module {expected_module!r}')
                if set(impl.get('functions', ())) != set(unit['fns']):
                    problems.append(
                        f'{mid}: implementation.functions '
                        f'{sorted(set(impl.get("functions", ())))} != registry '
                        f'{sorted(set(unit["fns"]))}')
                if set(impl.get('constants', ())) != set(unit.get('consts', ())):
                    problems.append(
                        f'{mid}: implementation.constants '
                        f'{sorted(set(impl.get("constants", ())))} != registry '
                        f'{sorted(set(unit.get("consts", ())))}')

        in_schema = (d.get('input') or {}).get('schema')
        if in_schema:
            try:
                iv = Draft202012Validator(in_schema)
                for i, ex in enumerate((d.get('input') or {}).get('examples') or []):
                    for e in iv.iter_errors(ex):
                        problems.append(
                            f'{mid}: input.examples[{i}]: '
                            f'{"/".join(str(x) for x in e.path)}: {e.message}')
            except Exception as exc:                                 # noqa: BLE001
                problems.append(f'{mid}: cannot validate examples: {exc}')
    return problems


def py_literal(values: list) -> str:
    return 'Literal[' + ', '.join(json.dumps(v) for v in values) + ']'


def enum_of(schema: dict, *path: str) -> list | None:
    node = schema
    for key in path:
        node = (node or {}).get(key) if isinstance(node, dict) else None
        if node is None:
            return None
    return node.get('enum') if isinstance(node, dict) else None


def render_python(descriptors: list[dict]) -> str:
    lines = ['"""' + BANNER + '"""', 'from __future__ import annotations', '',
             'from typing import Literal, TypedDict', '']
    ids = [d['method_id'] for d in descriptors]
    lines.append('MethodId = ' + py_literal(ids))
    lines.append('')
    for d in descriptors:
        mid = d['method_id']
        cls = ''.join(p.capitalize() for p in mid.replace('.', '_').split('_'))
        params = ((d['input']['schema'].get('properties') or {})
                  .get('parameters', {}).get('properties') or {})
        lines.append(f'# {mid} — {d["summary"]}')
        if params:
            lines.append(f'class {cls}Parameters(TypedDict, total=False):')
            for name, spec in params.items():
                if spec.get('enum'):
                    t = py_literal(spec['enum'])
                elif spec.get('type') == 'integer':
                    t = 'int'
                elif isinstance(spec.get('type'), list):
                    t = ' | '.join({'integer': 'int', 'number': 'float',
                                    'string': 'str', 'null': 'None'}.get(x, 'object')
                                   for x in spec['type'])
                else:
                    t = {'number': 'float', 'string': 'str',
                         'boolean': 'bool'}.get(spec.get('type'), 'object')
                lines.append(f'    {name}: {t}')
            lines.append('')
        # repr(), NOT json.dumps: JSON booleans are `true`/`false` and Python's are
        # `True`/`False`, so a json.dumps'd dict is a NameError the moment the
        # generated module is imported. Caught by importing the output rather than
        # reading it — the generated file looked completely reasonable.
        lines.append(f'{cls.upper()}_EXECUTION = {d["execution"]!r}')
        refusals = sorted({r['code'] for r in d.get('refusals', [])})
        lines.append(f'{cls.upper()}_REFUSALS = {refusals!r}')
        warns = sorted({w['code'] for w in d.get('warnings', [])})
        lines.append(f'{cls.upper()}_WARNINGS = {warns!r}')
        lines.append('')
    lines.append(f'METHOD_IDS = {ids!r}')
    lines.append('')
    return '\n'.join(lines)


_TS_SCHEMA_METADATA = {
    '$schema', '$id', '$anchor', '$defs', '$comment', 'title', 'description',
    'examples', 'default', 'deprecated', 'readOnly', 'writeOnly',
}


def _json_pointer_token(raw: str, reference: str) -> str:
    if re.search(r'~(?![01])', raw):
        raise SystemExit(
            f'gen_contracts: malformed JSON Pointer escape in local $ref {reference!r}')
    return raw.replace('~1', '/').replace('~0', '~')


def _resolve_local_ref(root: dict | bool, reference: object) -> dict | bool:
    """Resolve only descriptor-local `$defs` references, never a file or URI."""
    if not isinstance(reference, str) or not reference.startswith('#/$defs/'):
        raise SystemExit(
            f'gen_contracts: output $ref {reference!r} is not a descriptor-local '
            '`#/$defs/...` reference; remote and cross-document refs are forbidden')
    node: object = root
    for raw in reference[2:].split('/'):
        token = _json_pointer_token(raw, reference)
        if not isinstance(node, dict) or token not in node:
            raise SystemExit(
                f'gen_contracts: output $ref {reference!r} does not resolve in '
                'the descriptor schema')
        node = node[token]
    if not isinstance(node, (dict, bool)):
        raise SystemExit(
            f'gen_contracts: output $ref {reference!r} resolves to a non-schema value')
    return node


def _validate_ref_graph(root: dict | bool) -> None:
    """Reject every unresolved/remote/cyclic ref before emitting any partial type."""
    seen: set[tuple[int, tuple[str, ...]]] = set()

    def walk(node: object, stack: tuple[str, ...]) -> None:
        if isinstance(node, list):
            for item in node:
                walk(item, stack)
            return
        if not isinstance(node, dict):
            return
        marker = (id(node), stack)
        if marker in seen:
            return
        seen.add(marker)
        if '$ref' in node:
            reference = node['$ref']
            if not isinstance(reference, str):
                raise SystemExit('gen_contracts: output $ref must be a string')
            if reference in stack:
                cycle = ' -> '.join((*stack, reference))
                raise SystemExit(
                    f'gen_contracts: circular output $ref is forbidden: {cycle}')
            target = _resolve_local_ref(root, reference)
            walk(target, (*stack, reference))
        for key, value in node.items():
            if key != '$ref':
                walk(value, stack)

    walk(root, ())


def _ts_literal(value: object) -> str:
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if value is True:
        return 'true'
    if value is False:
        return 'false'
    if value is None:
        return 'null'
    return str(value)


def _ts_type(schema: dict | bool, root: dict | bool, indent: int,
             ref_stack: tuple[str, ...], aliases: dict[str, str]) -> str:
    if schema is True:
        return 'unknown'
    if schema is False:
        return 'never'
    if not isinstance(schema, dict):
        raise SystemExit(
            f'gen_contracts: output schema node must be an object or boolean, got '
            f'{type(schema).__name__}')

    if '$ref' in schema:
        reference = schema['$ref']
        if not isinstance(reference, str):
            raise SystemExit('gen_contracts: output $ref must be a string')
        if reference in ref_stack:
            cycle = ' -> '.join((*ref_stack, reference))
            raise SystemExit(
                f'gen_contracts: circular output $ref is forbidden: {cycle}')
        target = _resolve_local_ref(root, reference)
        resolved = (aliases[reference] if reference in aliases else
                    _ts_type(target, root, indent, (*ref_stack, reference), aliases))
        siblings = {key: value for key, value in schema.items()
                    if key != '$ref' and key not in _TS_SCHEMA_METADATA}
        if not siblings:
            return resolved
        sibling_type = _ts_type(siblings, root, indent, ref_stack, aliases)
        return resolved if sibling_type == 'unknown' else f'({resolved} & {sibling_type})'

    combinators: list[str] = []
    for keyword, operator in (('oneOf', ' | '), ('allOf', ' & ')):
        if keyword not in schema:
            continue
        branches = schema[keyword]
        if not isinstance(branches, list) or not branches:
            raise SystemExit(
                f'gen_contracts: output {keyword} must be a non-empty array of schemas')
        rendered = [_ts_type(branch, root, indent, ref_stack, aliases)
                    for branch in branches]
        combinators.append('(' + operator.join(rendered) + ')')

    base_schema = {key: value for key, value in schema.items()
                   if key not in {'oneOf', 'allOf'}
                   and key not in _TS_SCHEMA_METADATA}
    base = _ts_type_base(base_schema, root, indent, ref_stack, aliases)
    components = ([base] if base != 'unknown' else []) + combinators
    if components:
        return components[0] if len(components) == 1 else '(' + ' & '.join(components) + ')'
    return 'unknown'


def _ts_type_base(schema: dict, root: dict | bool, indent: int,
                  ref_stack: tuple[str, ...], aliases: dict[str, str]) -> str:
    """Render the non-combinator portion of a schema node."""
    pad = '    ' * indent
    if 'const' in schema:
        return _ts_literal(schema['const'])
    if 'enum' in schema:
        values = schema['enum']
        if not isinstance(values, list) or not values:
            raise SystemExit('gen_contracts: output enum must be a non-empty array')
        return ' | '.join(_ts_literal(value) for value in values)
    t = schema.get('type')
    if isinstance(t, list):
        if not t:
            raise SystemExit('gen_contracts: output type union must not be empty')
        return '(' + ' | '.join(
            _ts_type({**schema, 'type': one}, root, indent, ref_stack, aliases)
            for one in t) + ')'
    if t == 'null':
        return 'null'
    if t in ('number', 'integer'):
        return 'number'
    if t == 'string':
        return 'string'
    if t == 'boolean':
        return 'boolean'
    if t == 'array' or 'prefixItems' in schema or 'items' in schema:
        prefix = schema.get('prefixItems')
        if prefix is not None:
            if not isinstance(prefix, list):
                raise SystemExit('gen_contracts: output prefixItems must be an array')
            parts = [_ts_type(item, root, indent, ref_stack, aliases)
                     for item in prefix]
            maximum = schema.get('maxItems')
            items = schema.get('items', True)
            if maximum == len(prefix) or items is False:
                return '[' + ', '.join(parts) + ']'
            return ('[' + ', '.join(parts)
                    + (', ' if parts else '')
                    + f'...Array<{_ts_type(items, root, indent, ref_stack, aliases)}>]')
        return f'Array<{_ts_type(schema.get("items", True), root, indent, ref_stack, aliases)}>'
    if (t == 'object' or 'properties' in schema or 'required' in schema
            or 'additionalProperties' in schema):
        props = schema.get('properties') or {}
        if not isinstance(props, dict):
            raise SystemExit('gen_contracts: output properties must be an object')
        required_values = schema.get('required') or []
        if not isinstance(required_values, list) or not all(
                isinstance(value, str) for value in required_values):
            raise SystemExit('gen_contracts: output required must be a string array')
        required = set(required_values)
        if not props and not required:
            additional = schema.get('additionalProperties', True)
            if additional is False:
                return 'Record<string, never>'
            return f'Record<string, {_ts_type(additional, root, indent, ref_stack, aliases)}>'
        out = ['{']
        for key in list(props) + sorted(required - set(props)):
            value = props.get(key, True)
            opt = '' if key in required else '?'
            desc = ((value.get('description') or '').strip().replace('*/', '* /')
                    if isinstance(value, dict) else '')
            if desc:
                out.append(f'{pad}    /** {desc[:220]} */')
            rendered_key = key if re.fullmatch(r'[A-Za-z_$][A-Za-z0-9_$]*', key) \
                else json.dumps(key, ensure_ascii=False)
            out.append(
                f'{pad}    {rendered_key}{opt}: '
                f'{_ts_type(value, root, indent + 1, ref_stack, aliases)};')
        out.append(pad + '}')
        return '\n'.join(out)
    return 'unknown'


def ts_type(schema: dict | bool, indent: int = 0, *,
            root: dict | bool | None = None,
            aliases: dict[str, str] | None = None) -> str:
    """A JSON Schema fragment as a fail-closed TypeScript structural type.

    WHY GENERATE INSTEAD OF HAND-WRITING: the frontend carried a 26-field `FieldMeta`
    interface that a gate had to police against the backend key by key, because the type
    and the truth lived in two places. A generated type cannot drift — the drift check for
    it is `--check`, which fails when the file is stale, and that is one comparison rather
    than one per key.

    Descriptor-local `$defs`/`$ref`, `oneOf`, and `allOf` remain structural in the
    generated type.  Cross-document/remote, unknown, malformed, and circular refs fail
    generation rather than degrading to `any` or `unknown`.
    """
    if not isinstance(schema, (dict, bool)):
        raise SystemExit('gen_contracts: output schema root must be an object or boolean')
    root_schema = schema if root is None else root
    if not isinstance(root_schema, (dict, bool)):
        raise SystemExit('gen_contracts: output schema root must be an object or boolean')
    _validate_ref_graph(root_schema)
    return _ts_type(schema, root_schema, indent, (), aliases or {})


def _definition_aliases(output_name: str, schema: dict) -> dict[str, str]:
    definitions = schema.get('$defs') or {}
    if not isinstance(definitions, dict):
        raise SystemExit('gen_contracts: output $defs must be an object')
    aliases: dict[str, str] = {}
    for key in definitions:
        words = [word for word in re.split(r'[^A-Za-z0-9]+', key) if word]
        suffix = ''.join(word[:1].upper() + word[1:] for word in words) or 'Value'
        aliases[f'#/$defs/{key.replace("~", "~0").replace("/", "~1")}'] = (
            f'{output_name}Def{suffix}')
    if len(set(aliases.values())) != len(aliases):
        raise SystemExit(
            f'gen_contracts: output $defs in {output_name} collapse to duplicate '
            'TypeScript identifiers')
    return aliases


def render_typescript(descriptors: list[dict]) -> str:
    lines = ['/** ' + BANNER + ' */', '']
    lines.append('''/**
 * The v2 envelope, generated alongside the per-method output types.
 *
 * Hand-writing this in the frontend is how a renderer ends up reading keys the contract
 * does not promise: the previous flat `FieldMeta` carried 26 fields, a gate compared it to
 * the backend key by key, and it still drifted twice in one day.
 */
export type DiracEnvelope<TData = unknown> = {
    ok: boolean;
    data?: TData;
    artifacts?: Array<{
        id: string | null; sha256: string; role: string; media_type: string;
        size_bytes: number; encoding: string; url: string; metadata_url?: string;
        inline?: boolean; inline_base64?: string; method_version?: string | null;
        synthesised_by?: string;
    }>;
    warnings?: Array<{ code: string; message: string; affects?: string[] }>;
    error?: {
        code: string; message: string; user_message?: string; retryable?: boolean;
        caller_action?: string; details?: Record<string, unknown>;
        hint?: Record<string, unknown>;
    };
    meta?: {
        envelope?: number; method_id?: string; version?: string | null; cache?: string;
        seconds?: number; transport?: string; job_id?: string | null;
        parameters_used?: Record<string, unknown>;
        toolkits?: Record<string, string>;
        provenance?: Record<string, unknown>;
        [k: string]: unknown;
    };
};
''')
    ids = [d['method_id'] for d in descriptors]
    lines.append('export type MethodId =\n'
                 + '\n'.join(f"    | '{i}'" for i in ids) + ';')
    lines.append('')
    for d in descriptors:
        mid = d['method_id']
        name = ''.join(p.capitalize() for p in mid.replace('.', ' ').split())
        params = ((d['input']['schema'].get('properties') or {})
                  .get('parameters', {}).get('properties') or {})
        out_schema = (d.get('output') or {}).get('schema') or {}
        if out_schema.get('properties'):
            aliases = _definition_aliases(name + 'Output', out_schema)
            for definition_key, definition_schema in (
                    (out_schema.get('$defs') or {}).items()):
                reference = ('#/$defs/'
                             + definition_key.replace('~', '~0').replace('/', '~1'))
                lines.append(
                    f'type {aliases[reference]} = '
                    + ts_type(definition_schema, root=out_schema, aliases=aliases)
                    + ';')
                lines.append('')
            lines.append(f'/** {mid} output — generated from its declared output schema. '
                         f'The renderer reads THIS, not a hand-kept mirror of it. */')
            lines.append(f'export type {name}Output = '
                         + ts_type(out_schema, root=out_schema, aliases=aliases) + ';')
            lines.append('')
        lines.append(f'/** {mid} — {d["summary"]} */')
        if params:
            lines.append(f'export interface {name}Parameters {{')
            for pname, spec in params.items():
                if spec.get('enum'):
                    t = ' | '.join(f"'{v}'" for v in spec['enum'])
                elif isinstance(spec.get('type'), list):
                    t = ' | '.join({'integer': 'number', 'number': 'number',
                                    'string': 'string', 'null': 'null'}.get(x, 'unknown')
                                   for x in spec['type'])
                else:
                    t = {'integer': 'number', 'number': 'number', 'string': 'string',
                         'boolean': 'boolean'}.get(spec.get('type'), 'unknown')
                lines.append(f'    {pname}?: {t};')
            lines.append('}')
            lines.append('')
        lines.append(f'export const {name}Execution = '
                     + json.dumps(d['execution'], indent=4) + ' as const;')
        lines.append('')
    lines.append('export const METHOD_IDS: readonly MethodId[] = '
                 + json.dumps(ids, indent=4) + ' as const;')
    lines.append('')
    return '\n'.join(lines)


def main() -> int:
    check = '--check' in sys.argv
    descriptors = load_descriptors()
    if not descriptors:
        print('gen_contracts: no descriptors in contracts/methods — refusing to '
              'write empty generated files, which would read as "nothing to do"',
              file=sys.stderr)
        return 2

    problems = validate(descriptors)
    if problems:
        print(f'{len(problems)} contract problem(s):', file=sys.stderr)
        for p in problems[:20]:
            print(f'  {p}', file=sys.stderr)
        return 1

    want = {OUT_PY: render_python(descriptors), OUT_TS: render_typescript(descriptors)}
    stale = []
    for path, text in want.items():
        current = path.read_text(encoding='utf-8') if path.exists() else None
        if current != text:
            stale.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding='utf-8')

    rel = lambda p: p.relative_to(ROOT)                              # noqa: E731
    if check and stale:
        print('GENERATED FILES ARE STALE: ' + ', '.join(str(rel(p)) for p in stale),
              file=sys.stderr)
        print('Run: python3 scripts/gen_contracts.py', file=sys.stderr)
        return 1
    verb = 'up to date' if check else ('wrote ' + ', '.join(str(rel(p)) for p in stale)
                                       if stale else 'already current')
    print(f'{len(descriptors)} descriptor(s) valid · {verb}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
