/* eslint-disable quotes */
// Generated by scripts/compile-molecular-nodes.mjs. Do not hand-edit.
export const MolecularNodesCompiledManifest = Object.freeze({
    "artifact": {
        "algorithm": "sha256",
        "hash": "7121d59fa574a0806984d8a25ebb0d661d27d380475094a9b12685192de3d6a2"
    },
    "bundleFile": "mn-r4.bundle.json",
    "programs": [
        {
            "entry": "group-style-ball-and-stick-4c5d93df",
            "id": "program-style-ball-and-stick-4c5d93df",
            "kind": "ball-and-stick",
            "name": "Style Ball and Stick"
        },
        {
            "entry": "group-style-cartoon-77ea96a8",
            "id": "program-style-cartoon-77ea96a8",
            "kind": "cartoon",
            "name": "Style Cartoon"
        },
        {
            "entry": "group-style-preset-1-a57929c8",
            "id": "program-style-preset-1-a57929c8",
            "kind": "preset-1",
            "name": "Style Preset 1"
        },
        {
            "entry": "group-style-preset-2-042c3dc9",
            "id": "program-style-preset-2-042c3dc9",
            "kind": "preset-2",
            "name": "Style Preset 2"
        },
        {
            "entry": "group-style-preset-3-d96ed738",
            "id": "program-style-preset-3-d96ed738",
            "kind": "preset-3",
            "name": "Style Preset 3"
        },
        {
            "entry": "group-style-preset-4-da64893b",
            "id": "program-style-preset-4-da64893b",
            "kind": "preset-4",
            "name": "Style Preset 4"
        },
        {
            "entry": "group-style-ribbon-c6345a0b",
            "id": "program-style-ribbon-c6345a0b",
            "kind": "ribbon",
            "name": "Style Ribbon"
        },
        {
            "entry": "group-style-spheres-f10dfb5d",
            "id": "program-style-spheres-f10dfb5d",
            "kind": "spheres",
            "name": "Style Spheres"
        },
        {
            "entry": "group-style-sticks-4004220e",
            "id": "program-style-sticks-4004220e",
            "kind": "sticks",
            "name": "Style Sticks"
        },
        {
            "entry": "group-style-surface-e3044e30",
            "id": "program-style-surface-e3044e30",
            "kind": "surface",
            "name": "Style Surface"
        }
    ],
    "runtime": {
        "bufferLayouts": {
            "atom": {
                "fields": {
                    "color": "vec4<f32>@16",
                    "metadata": "vec4<u32>@32",
                    "positionRadius": "vec4<f32>@0"
                },
                "stride": 48
            },
            "bond": {
                "fields": {
                    "atomIndices": "vec2<u32>@0",
                    "metadata": "vec2<u32>@8",
                    "radii": "vec2<f32>@16"
                },
                "stride": 32
            },
            "compactInstance": {
                "fields": {
                    "color": "vec4<f32>@16",
                    "metadata": "vec4<u32>@32",
                    "positionRadius": "vec4<f32>@0"
                },
                "stride": 48
            },
            "curvePoint": {
                "fields": {
                    "normal": "vec4<f32>@32",
                    "positionRadius": "vec4<f32>@0",
                    "tangent": "vec4<f32>@16"
                },
                "stride": 48
            },
            "selectionWord": {
                "fields": {
                    "bits": "u32@0"
                },
                "stride": 4
            }
        },
        "kernels": [
            {
                "id": "update-instances",
                "source": "kernels/update-instances.wgsl",
                "stage": "compute",
                "workgroupSize": 64
            },
            {
                "id": "curve-extrude",
                "source": "kernels/curve-extrude.wgsl",
                "stage": "compute",
                "workgroupSize": 64
            },
            {
                "id": "selection-bitset",
                "source": "kernels/selection-bitset.wgsl",
                "stage": "compute",
                "workgroupSize": 64
            }
        ]
    },
    "schema": "molecular-representation-aot@1",
    "source": {
        "allNodeGroups": 524,
        "asset": "node_data_file.blend",
        "blender": "5.2.0 LTS",
        "upstreamCommit": "5b52da2e29a07fd3e8f545f70c252ace591375bb",
        "upstreamRepository": "https://github.com/BradyAJohnston/MolecularNodes",
        "upstreamVersion": "5.2.0"
    },
    "stats": {
        "eliminatedNodes": 154,
        "foldedConstants": 3,
        "groups": 173,
        "links": 2998,
        "materials": 8,
        "programs": 10,
        "retainedNodes": 2255,
        "sourceNodes": 2409
    }
} as const);
